Repository lambdaclass/ethrex, pull requests merged in 2024-10, with the labels that each got.

#583 feat: (levm) Implement different call types
  crates/levm/.gitignore
  crates/levm/src/call_frame.rs
  crates/levm/src/memory.rs
  crates/levm/src/opcodes.rs
  crates/levm/src/operations.rs
  crates/levm/src/primitives.rs
  crates/levm/src/vm.rs
  crates/levm/tests/tests.rs
Labels: opcode

#584 feat(levm): opcodes gas consumption
  crates/levm/src/call_frame.rs
  crates/levm/src/constants.rs
  crates/levm/src/memory.rs
  crates/levm/src/opcodes.rs
  crates/levm/src/operations.rs
  crates/levm/src/vm.rs
  crates/levm/tests/tests.rs
  crates/levm/tests/vm_tests.rs
Labels: opcode

#640 feat(levm): vm interface
  crates/levm/src/lib.rs
  crates/levm/src/transaction.rs
  crates/levm/src/vm.rs
  crates/levm/tests/operations_tests.rs
  crates/levm/tests/tests.rs
  crates/levm/tests/vm_tests.rs
Labels: levm

#626 docs(levm): add `README` and `Makefile`
  crates/levm/Makefile
  crates/levm/README.md
Labels: documentation

#704 LEVM: Fix SMod Opcode
  crates/levm/src/vm.rs
  crates/levm/tests/tests.rs
Labels: levm

#567 feat: rpc endpoint 'eth_newFilter'
  .gitignore
  Cargo.toml
  crates/networking/rpc/Cargo.toml
  crates/networking/rpc/eth/filter.rs
  crates/networking/rpc/eth/logs.rs
  crates/networking/rpc/eth/mod.rs
  crates/networking/rpc/rpc.rs
  crates/networking/rpc/utils.rs
Labels: rpc-api

#709 feat(L2): add L1 tx sender
  crates/common/types/mod.rs
  crates/l2/Cargo.toml
  crates/l2/operator/l1_tx_sender.rs
  crates/l2/rpc/l1_rpc.rs
  crates/l2/rpc/mod.rs
  crates/l2/rpc/transaction.rs
Labels: L2

#712 refactor(levm): refactor Opcodes LEVM
  crates/vm/levm/src/lib.rs
  crates/vm/levm/src/opcode_handlers/bitwise_comparison.rs
  crates/vm/levm/src/opcode_handlers/block.rs
  crates/vm/levm/src/opcode_handlers/dup.rs
  crates/vm/levm/src/opcode_handlers/environment.rs
  crates/vm/levm/src/opcode_handlers/exchange.rs
  crates/vm/levm/src/opcode_handlers/keccak.rs
  crates/vm/levm/src/opcode_handlers/logging.rs
  crates/vm/levm/src/opcode_handlers/mod.rs
  crates/vm/levm/src/opcode_handlers/push.rs
  crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs
  crates/vm/levm/src/opcode_handlers/stop_and_arithmetic.rs
  crates/vm/levm/src/opcode_handlers/system.rs
  crates/vm/levm/src/vm.rs
  crates/vm/levm/src/vm_result.rs
  crates/vm/levm/tests/tests.rs
Labels: levm

#670 feat(levm): add benchmarks comparison with `revm`
  .github/workflows/levm_bench.yaml
  Cargo.toml
  crates/vm/levm/Cargo.toml
  crates/vm/levm/Makefile
  crates/vm/levm/bench/revm_comparison/Cargo.toml
  crates/vm/levm/bench/revm_comparison/README.md
  crates/vm/levm/bench/revm_comparison/src/levm_factorial.rs
  crates/vm/levm/bench/revm_comparison/src/levm_fibonacci.rs
  crates/vm/levm/bench/revm_comparison/src/lib.rs
  crates/vm/levm/bench/revm_comparison/src/revm_factorial.rs
  crates/vm/levm/bench/revm_comparison/src/revm_fibonacci.rs
  crates/vm/levm/src/lib.rs
  crates/vm/levm/src/utils.rs
  crates/vm/levm/tests/tests.rs
Labels: levm

#586 feat(L2): basic sequencer
  Cargo.toml
  cmd/ethereum_rust/ethereum_rust.rs
  crates/common/serde_utils.rs
  crates/common/types/blobs_bundle.rs
  crates/l2/Cargo.toml
  crates/l2/operator/block_producer.rs
  crates/l2/operator/engine.rs
  crates/l2/operator/mod.rs
  crates/networking/rpc/Cargo.toml
  crates/networking/rpc/engine/fork_choice.rs
  crates/networking/rpc/engine/mod.rs
  crates/networking/rpc/engine/payload.rs
  crates/networking/rpc/eth/block.rs
  crates/networking/rpc/eth/transaction.rs
  crates/networking/rpc/rpc.rs
  crates/networking/rpc/types/fork_choice.rs
  crates/networking/rpc/types/payload.rs
  crates/networking/rpc/utils.rs
  test_data/genesis-execution-api.json
Labels: L2

#730 fix(L2): readme
  README.md
  crates/l2/README.md
  crates/l2/docs/prover.md
Labels: documentation, L2

#732 feat(config): take config from env vars
  crates/l2/Cargo.toml
  crates/l2/docs/README.md
  crates/l2/docs/operator.md
  crates/l2/docs/prover.md
  crates/l2/operator/block_producer.rs
  crates/l2/operator/l1_tx_sender.rs
  crates/l2/operator/l1_watcher.rs
  crates/l2/operator/mod.rs
  crates/l2/operator/proof_data_provider.rs
  crates/l2/prover/mod.rs
  crates/l2/prover/proof_data_client.rs
  crates/l2/prover/prover.rs
  crates/l2/prover/sp1/program/.gitignore
  crates/l2/prover/sp1/program/elf/riscv32im-succinct-zkvm-elf
  crates/l2/utils/config/block_producer.rs
  crates/l2/utils/config/engine_api.rs
  crates/l2/utils/config/eth.rs
  crates/l2/utils/config/l1_tx_sender.rs
  crates/l2/utils/config/l1_watcher.rs
  crates/l2/utils/config/mod.rs
  crates/l2/utils/config/proof_data_provider.rs
  crates/l2/utils/config/prover.rs
  crates/l2/utils/engine_client/mod.rs
  crates/l2/utils/eth_client/mod.rs
  crates/l2/utils/mod.rs
Labels: L2

#600 feat: (levm) Ethereum Foundation Tests
  .github/workflows/levm_ef_tests.yaml
  .gitignore
  Makefile
  crates/vm/levm/.ethtest_shasum
  crates/vm/levm/.ethtest_version
  crates/vm/levm/.gitignore
  crates/vm/levm/Cargo.toml
  crates/vm/levm/Makefile
  crates/vm/levm/bench/revm_comparison/src/lib.rs
  crates/vm/levm/rust-toolchain.toml
  crates/vm/levm/src/constants.rs
  crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs
  crates/vm/levm/src/vm.rs
  crates/vm/levm/src/vm_result.rs
  crates/vm/levm/tests/ef_tests.rs
  crates/vm/levm/tests/ef_tests_executor/mod.rs
  crates/vm/levm/tests/ef_tests_executor/models.rs
  crates/vm/levm/tests/ef_tests_executor/parser.rs
  crates/vm/levm/tests/ef_tests_executor/primitives.rs
  crates/vm/levm/tests/ef_tests_executor/test_utils.rs
  crates/vm/levm/tests/tests.rs
Labels: levm

#624 fix(levm): replace push32 with push(n)
  crates/vm/levm/src/operations.rs
  crates/vm/levm/src/vm.rs
  crates/vm/levm/tests/tests.rs
Labels: levm

#697 feat(levm): environment opcodes
  crates/vm/levm/src/constants.rs
  crates/vm/levm/src/opcode_handlers/block.rs
  crates/vm/levm/src/opcodes.rs
  crates/vm/levm/src/operations.rs
  crates/vm/levm/src/transaction.rs
  crates/vm/levm/src/vm.rs
  crates/vm/levm/tests/tests.rs
Labels: levm

#713 feat(levm): opcodes `CALLVALUE`, `CODESIZE`, `CODECOPY` & `GASPRICE`
  crates/vm/levm/src/constants.rs
  crates/vm/levm/src/opcode_handlers/block.rs
  crates/vm/levm/src/opcodes.rs
  crates/vm/levm/src/operations.rs
  crates/vm/levm/src/vm.rs
  crates/vm/levm/src/vm_result.rs
  crates/vm/levm/tests/tests.rs
Labels: levm

#734 feat(L2): deposits support
  Cargo.toml
  cmd/ethereum_rust/Cargo.toml
  cmd/ethereum_rust/ethereum_rust.rs
  crates/l2/contracts/src/l1/CommonBridge.sol
  crates/l2/contracts/src/l1/interfaces/ICommonBridge.sol
  crates/l2/contracts/test/l1/Deposit.t.sol
  crates/l2/operator/l1_watcher.rs
  crates/l2/operator/mod.rs
  crates/l2/utils/config/l1_tx_sender.rs
  crates/l2/utils/config/l1_watcher.rs
  crates/l2/utils/config/mod.rs
  crates/l2/utils/eth_client/mod.rs
  crates/vm/evm/Cargo.toml
  crates/vm/evm/evm.rs
  crates/vm/evm/mods.rs
Labels: L2

#672 feat(L2): connect components
  crates/l2/contracts/src/l1/BlockExecutor.sol
  crates/l2/contracts/src/l1/interfaces/IBlockExecutor.sol
  crates/l2/docs/operator.md
  crates/l2/operator/block_producer.rs
  crates/l2/operator/l1_tx_sender.rs
  crates/l2/operator/l1_watcher.rs
  crates/l2/operator/mod.rs
  crates/l2/operator/proof_data_provider.rs
  crates/l2/prover/proof_data_client.rs
  crates/l2/prover/prover.rs
  crates/l2/utils/config/block_producer.rs
  crates/l2/utils/config/mod.rs
  crates/l2/utils/config/operator.rs
  crates/l2/utils/eth_client/mod.rs
  crates/networking/rpc/types/receipt.rs
Labels: L2

#810 fix(L2): several fixes
  cmd/ethereum_rust_l2/src/commands/stack.rs
  cmd/ethereum_rust_l2/src/commands/wallet.rs
  cmd/ethereum_rust_l2/src/utils/config/mod.rs
  crates/l2/operator/mod.rs
  crates/l2/utils/config/operator.rs
Labels: L2

#805 feat(l2): add load test command to CLI
  cmd/ethereum_rust_l2/Cargo.toml
  cmd/ethereum_rust_l2/src/cli.rs
  cmd/ethereum_rust_l2/src/commands/mod.rs
  cmd/ethereum_rust_l2/src/commands/test.rs
  crates/l2/docs/README.md
  test_data/genesis-l2.json
  test_data/private_keys.txt
Labels: L2

#792 fix(levm): call with no code in address
  crates/vm/levm/src/opcode_handlers/system.rs
  crates/vm/levm/src/vm.rs
  crates/vm/levm/src/vm_result.rs
Labels: levm

#846 chore(l2): prevent Hive workflow to execute on L2-only changes
  .github/workflows/hive.yaml
Labels: ef-tests, L2

#842 feat(l2): load `.env` file
  .gitignore
  cmd/ethereum_rust_l2/src/commands/stack.rs
  crates/l2/.example.env
  crates/l2/.gitignore
  crates/l2/docs/operator.md
  crates/l2/operator/mod.rs
  crates/l2/utils/config/errors.rs
  crates/l2/utils/config/mod.rs
Labels: L2

#851 fix(l2): gracefully stop `ProofDataProvider`
  crates/l2/operator/proof_data_provider.rs
  crates/l2/utils/config/proof_data_provider.rs
Labels: L2

#859 fix(l2): remove duplicated `eth_gasPrice` client implementation
  cmd/ethereum_rust_l2/src/commands/wallet.rs
  crates/l2/operator/l1_watcher.rs
  crates/l2/operator/mod.rs
  crates/l2/utils/eth_client/errors.rs
  crates/l2/utils/eth_client/mod.rs
Labels: L2

#861 feat(levm): `STOP` opcode
  crates/vm/levm/src/opcode_handlers/arithmetic.rs
  crates/vm/levm/src/opcode_handlers/mod.rs
  crates/vm/levm/src/vm.rs
Labels: levm

#869 feat(levm): add `levm` crate
  .github/workflows/levm_bench.yaml
  Cargo.toml
  crates/vm/levm/.gitignore
  crates/vm/levm/Cargo.toml
  crates/vm/levm/Makefile
  crates/vm/levm/README.md
  crates/vm/levm/bench/revm_comparison/Cargo.toml
  crates/vm/levm/bench/revm_comparison/README.md
  crates/vm/levm/bench/revm_comparison/src/levm_factorial.rs
  crates/vm/levm/bench/revm_comparison/src/levm_fibonacci.rs
  crates/vm/levm/bench/revm_comparison/src/lib.rs
  crates/vm/levm/bench/revm_comparison/src/revm_factorial.rs
  crates/vm/levm/bench/revm_comparison/src/revm_fibonacci.rs
  crates/vm/levm/rust-toolchain.toml
  crates/vm/levm/src/block.rs
  crates/vm/levm/src/call_frame.rs
  crates/vm/levm/src/constants.rs
  crates/vm/levm/src/errors.rs
  crates/vm/levm/src/lib.rs
  crates/vm/levm/src/memory.rs
  crates/vm/levm/src/opcode_handlers/arithmetic.rs
  crates/vm/levm/src/opcode_handlers/bitwise_comparison.rs
  crates/vm/levm/src/opcode_handlers/block.rs
  crates/vm/levm/src/opcode_handlers/dup.rs
  crates/vm/levm/src/opcode_handlers/environment.rs
  crates/vm/levm/src/opcode_handlers/exchange.rs
  crates/vm/levm/src/opcode_handlers/keccak.rs
  crates/vm/levm/src/opcode_handlers/logging.rs
  crates/vm/levm/src/opcode_handlers/mod.rs
  crates/vm/levm/src/opcode_handlers/push.rs
  crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs
  crates/vm/levm/src/opcode_handlers/system.rs
  crates/vm/levm/src/opcodes.rs
  crates/vm/levm/src/operations.rs
  crates/vm/levm/src/primitives.rs
  crates/vm/levm/src/utils.rs
  crates/vm/levm/src/vm.rs
  crates/vm/levm/tests/lib.rs
  crates/vm/levm/tests/tests.rs
Labels: levm

#887 docs(l2): add Docker prerequisite
  crates/l2/README.md
Labels: documentation, L2

#886 docs(levm): update README
  crates/vm/levm/README.md
Labels: levm

#890 feat(l2): use `ethereum_rust` dev as local L1
  Cargo.toml
  cmd/ethereum_rust/Cargo.toml
  cmd/ethereum_rust/ethereum_rust.rs
  cmd/ethereum_rust_l2/src/commands/stack.rs
  cmd/ethereum_rust_l2/src/commands/test.rs
  crates/blockchain/dev/Cargo.toml
  crates/blockchain/dev/Dockerfile
  crates/blockchain/dev/block_producer.rs
  crates/blockchain/dev/dev.rs
  crates/blockchain/dev/docker-compose-dev.yaml
  crates/blockchain/dev/utils/engine_client/config.rs
  crates/blockchain/dev/utils/engine_client/errors.rs
  crates/blockchain/dev/utils/engine_client/mod.rs
  crates/blockchain/dev/utils/mod.rs
  crates/common/types/transaction.rs
  crates/l2/Cargo.toml
  crates/l2/docker-compose-l2.yml
  crates/l2/operator/errors.rs
  crates/l2/operator/mod.rs
  crates/l2/utils/config/mod.rs
  crates/l2/utils/eth_client/mod.rs
  crates/l2/utils/mod.rs
  crates/networking/rpc/eth/gas_price.rs
  test_data/genesis-l1.json
Labels: L2

#901 refactor(l2): replace placeholder names
  crates/l2/.example.env
  crates/l2/Makefile
  crates/l2/README.md
  crates/l2/contracts/script/DeployL1.s.sol
  crates/l2/contracts/src/l1/OnChainOperator.sol
  crates/l2/contracts/src/l1/interfaces/IOnChainOperator.sol
  crates/l2/contracts/test/l1/BlockExecutor.t.sol
  crates/l2/docs/contracts.md
  crates/l2/docs/operator.md
  crates/l2/docs/prover.md
  crates/l2/operator/mod.rs
  crates/l2/operator/prover_server.rs
  crates/l2/prover/mod.rs
  crates/l2/prover/prover.rs
  crates/l2/prover/prover_client.rs
  crates/l2/utils/config/mod.rs
  crates/l2/utils/config/prover_client.rs
  crates/l2/utils/config/prover_server.rs
Labels: L2

#908 feat(levm): remove Option in gasprice
  crates/vm/levm/src/opcode_handlers/block.rs
  crates/vm/levm/src/vm.rs
  crates/vm/levm/tests/tests.rs
Labels: levm

#919 feat(levm): improve Gas Logic
  crates/vm/levm/src/call_frame.rs
  crates/vm/levm/src/opcode_handlers/arithmetic.rs
  crates/vm/levm/src/opcode_handlers/bitwise_comparison.rs
  crates/vm/levm/src/opcode_handlers/block.rs
  crates/vm/levm/src/opcode_handlers/dup.rs
  crates/vm/levm/src/opcode_handlers/environment.rs
  crates/vm/levm/src/opcode_handlers/exchange.rs
  crates/vm/levm/src/opcode_handlers/keccak.rs
  crates/vm/levm/src/opcode_handlers/logging.rs
  crates/vm/levm/src/opcode_handlers/push.rs
  crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs
  crates/vm/levm/src/opcode_handlers/system.rs
  crates/vm/levm/src/vm.rs
Labels: levm

#907 feat(levm): improve blobbasefee opcode
  crates/vm/levm/src/constants.rs
  crates/vm/levm/src/opcode_handlers/block.rs
  crates/vm/levm/src/utils.rs
  crates/vm/levm/src/vm.rs
  crates/vm/levm/tests/tests.rs
Labels: levm

#925 fix(levm): change Makefile's lint
  crates/vm/levm/Makefile
Labels: levm

#937 feat(l2): improve `Makefile`
  crates/l2/Makefile
  crates/l2/README.md
Labels: L2

#921 feat(levm): add transact validations
  crates/vm/levm/src/constants.rs
  crates/vm/levm/src/errors.rs
  crates/vm/levm/src/vm.rs
Labels: levm

#910 refactor(levm): move opcodes to their corresponding folder (#863)
  crates/vm/levm/src/opcode_handlers/block.rs
  crates/vm/levm/src/opcode_handlers/environment.rs
Labels: levm

#918 feat(l2): add transaction commands
  cmd/ethereum_rust_l2/Cargo.toml
  cmd/ethereum_rust_l2/src/cli.rs
  cmd/ethereum_rust_l2/src/commands/mod.rs
  cmd/ethereum_rust_l2/src/commands/utils.rs
  cmd/ethereum_rust_l2/src/commands/wallet.rs
  crates/common/types/transaction.rs
  crates/l2/utils/eth_client/errors.rs
  crates/l2/utils/eth_client/mod.rs
Labels: L2, CLI

#951 fix(l2): add clippy suggestions
  cmd/ethereum_rust_l2/src/commands/test.rs
Labels: L2

#939 refactor(l2): new zkvm
  cmd/ethereum_rust/ethereum_rust.rs
  cmd/ethereum_rust_l2/src/commands/stack.rs
  crates/l2/.example.env
  crates/l2/.example.envrc
  crates/l2/Cargo.toml
  crates/l2/Makefile
  crates/l2/proposer/prover_server.rs
  crates/l2/prover/Cargo.toml
  crates/l2/prover/build.rs
  crates/l2/prover/program/.gitignore
  crates/l2/prover/program/Cargo.toml
  crates/l2/prover/program/NOTICE
  crates/l2/prover/program/interface/Cargo.toml
  crates/l2/prover/program/interface/build.rs
  crates/l2/prover/program/interface/guest/Cargo.toml
  crates/l2/prover/program/interface/guest/src/main.rs
  crates/l2/prover/program/interface/src/lib.rs
  crates/l2/prover/program/src/main.rs
  crates/l2/prover/src/main.rs
  crates/l2/prover/src/prover.rs
  crates/l2/prover/src/prover_client.rs
Labels: L2

#944 feat(l2): prepare contracts for withdraw
  crates/l2/Makefile
  crates/l2/contracts/script/DeployL1.s.sol
  crates/l2/contracts/script/Utils.sol
  crates/l2/contracts/src/l1/CommonBridge.sol
  crates/l2/contracts/src/l1/OnChainProposer.sol
  crates/l2/contracts/src/l1/interfaces/ICommonBridge.sol
  crates/l2/contracts/src/l1/interfaces/IOnChainProposer.sol
Labels: L2

#930 feat(levm): implement Transaction Report
  crates/vm/levm/README.md
  crates/vm/levm/bench/revm_comparison/src/lib.rs
  crates/vm/levm/docs/callframe.md
  crates/vm/levm/src/call_frame.rs
  crates/vm/levm/src/errors.rs
  crates/vm/levm/src/memory.rs
  crates/vm/levm/src/opcode_handlers/environment.rs
  crates/vm/levm/src/utils.rs
  crates/vm/levm/src/vm.rs
  crates/vm/levm/tests/tests.rs
Labels: levm

#950 feat(l2): prepare proposer for withdraw
  crates/l2/Makefile
  crates/l2/contracts/src/l1/interfaces/ICommonBridge.sol
  crates/l2/contracts/src/l1/interfaces/IOnChainProposer.sol
  crates/l2/proposer/mod.rs
  crates/storage/store/storage.rs
Labels: L2

#940 feat(levm): implement blobhash logic
  crates/vm/levm/src/errors.rs
  crates/vm/levm/src/opcode_handlers/block.rs
  crates/vm/levm/src/utils.rs
  crates/vm/levm/src/vm.rs
  crates/vm/levm/tests/tests.rs
Labels: levm

#878 refactor(l2): new prover structure
  .github/workflows/ci.yaml
  Cargo.toml
  cmd/ethereum_rust/ethereum_rust.rs
  cmd/ethereum_rust_l2/Cargo.toml
  cmd/ethereum_rust_l2/src/commands/stack.rs
  crates/l2/.example.env
  crates/l2/Cargo.toml
  crates/l2/Makefile
  crates/l2/docs/README.md
  crates/l2/docs/contracts.md
  crates/l2/docs/proposer.md
  crates/l2/docs/prover.md
  crates/l2/l2.rs
  crates/l2/proposer/errors.rs
  crates/l2/proposer/mod.rs
  crates/l2/proposer/prover_server.rs
  crates/l2/prover/Cargo.toml
  crates/l2/prover/mod.rs
  crates/l2/prover/prover.rs
  crates/l2/prover/sp1/lib/Cargo.toml
  crates/l2/prover/sp1/lib/src/lib.rs
  crates/l2/prover/sp1/program/.gitignore
  crates/l2/prover/sp1/program/Cargo.toml
  crates/l2/prover/sp1/program/src/main.rs
  crates/l2/prover/src/lib.rs
  crates/l2/prover/src/main.rs
  crates/l2/prover/src/prover.rs
  crates/l2/prover/src/prover_client.rs
  crates/l2/prover/src/utils/placeholder.rs
  crates/l2/prover/zkvm/.gitignore
  crates/l2/prover/zkvm/Cargo.toml
  crates/l2/prover/zkvm/NOTICE
  crates/l2/prover/zkvm/interface/Cargo.toml
  crates/l2/prover/zkvm/interface/build.rs
  crates/l2/prover/zkvm/interface/guest/Cargo.toml
  crates/l2/prover/zkvm/interface/guest/src/main.rs
  crates/l2/prover/zkvm/interface/src/lib.rs
  crates/l2/utils/config/eth.rs
  crates/l2/utils/config/prover_client.rs
Labels: L2

#967 feat(l2): get withdrawal merkle proof
  cmd/ethereum_rust_l2/src/commands/wallet.rs
  crates/common/types/transaction.rs
  crates/l2/proposer/mod.rs
  crates/l2/utils/eth_client/errors.rs
  crates/l2/utils/eth_client/mod.rs
  crates/l2/utils/merkle_tree.rs
Labels: L2

#976 fix(l2): deployer script fixes
  crates/l2/.env.example
  crates/l2/contracts/deployer.rs
Labels: L2

#985 feat(l2): add `l2` crate to workspace members
  Cargo.toml
Labels: L2

#983 fix(l2): `help` target default when doing `make`
  crates/l2/Makefile
  crates/l2/README.md
Labels: L2

#988 chore(l2): skip assertoor CI on l2-only changes
  .github/workflows/assertoor.yaml
Labels: L2

#984 refactor(l2): `cli` target
  crates/l2/Makefile
Labels: L2

#877 feat(l2): withdrawal handling
  cmd/ethereum_rust_l2/Cargo.toml
  cmd/ethereum_rust_l2/src/commands/utils.rs
  cmd/ethereum_rust_l2/src/commands/wallet.rs
  crates/common/types/receipt.rs
  crates/common/types/transaction.rs
  crates/l2/Makefile
  crates/l2/contracts/deployer.rs
  crates/l2/contracts/src/l1/CommonBridge.sol
  crates/l2/contracts/src/l1/OnChainProposer.sol
  crates/l2/contracts/src/l1/interfaces/ICommonBridge.sol
  crates/l2/contracts/src/l1/interfaces/IOnChainProposer.sol
  crates/l2/proposer/l1_watcher.rs
  crates/l2/proposer/mod.rs
  crates/l2/utils/eth_client/errors.rs
  crates/l2/utils/eth_client/eth_sender.rs
  crates/l2/utils/eth_client/mod.rs
  crates/l2/utils/eth_client/transaction.rs
  crates/l2/utils/merkle_tree.rs
  crates/l2/utils/mod.rs
  crates/networking/rpc/eth/fee_market.rs
  crates/networking/rpc/types/transaction.rs
  crates/storage/store/storage.rs
  crates/vm/Cargo.toml
  crates/vm/mods.rs
  crates/vm/vm.rs
Labels: L2

#990 feat(levm): add contract creation
  crates/vm/levm/.gitignore
  crates/vm/levm/src/constants.rs
  crates/vm/levm/src/errors.rs
  crates/vm/levm/src/utils.rs
  crates/vm/levm/src/vm.rs
  crates/vm/levm/tests/tests.rs
Labels: levm

#1010 feat(l2): `make restart` does not clean contract deps
  crates/l2/Makefile
Labels: L2

#1022 fix(l2): `wallet transfer`
  cmd/ethereum_rust_l2/src/commands/wallet.rs
Labels: L2, CLI

#1036 refactor(l2): add `-w` flag to cmds that send txs
  cmd/ethereum_rust_l2/src/commands/wallet.rs
Labels: L2, CLI

#991 feat(levm): implement `Cache` and refactor `Db`
  crates/vm/levm/Cargo.toml
  crates/vm/levm/docs/substate.md
  crates/vm/levm/src/call_frame.rs
  crates/vm/levm/src/constants.rs
  crates/vm/levm/src/db.rs
  crates/vm/levm/src/lib.rs
  crates/vm/levm/src/opcode_handlers/block.rs
  crates/vm/levm/src/opcode_handlers/environment.rs
  crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs
  crates/vm/levm/src/opcode_handlers/system.rs
  crates/vm/levm/src/utils.rs
  crates/vm/levm/src/vm.rs
  crates/vm/levm/tests/tests.rs
Labels: levm

#969 feat(l2): standalone test for prover
  .github/workflows/ci.yaml
  .github/workflows/l2_prover_ci.yaml
  Makefile
  crates/l2/Makefile
  crates/l2/docs/prover.md
  crates/l2/prover/Cargo.toml
  crates/l2/prover/Makefile
  crates/l2/prover/src/prover.rs
  crates/l2/prover/tests/perf_zkvm.rs
  crates/l2/prover/zkvm/interface/guest/Cargo.toml
  crates/l2/prover/zkvm/interface/guest/src/main.rs
  crates/l2/utils/mod.rs
  crates/l2/utils/test_data_io.rs
  test_data/l2-loadtest.rlp
Labels: L2
