Repository lambdaclass/ethrex, pull requests merged in 2025-07, with the labels that each got.

#3344 feat(l2): replace custom merkle tree with `OpenZeppelin` + `lambdaworks`
  Cargo.lock
  Cargo.toml
  crates/l2/common/Cargo.toml
  crates/l2/common/src/l1_messages.rs
  crates/l2/common/src/lib.rs
  crates/l2/common/src/merkle_tree.rs
  crates/l2/common/src/state_diff.rs
  crates/l2/contracts/src/l1/CommonBridge.sol
  crates/l2/contracts/src/l1/interfaces/ICommonBridge.sol
  crates/l2/contracts/src/l2/CommonBridgeL2.sol
  crates/l2/contracts/src/l2/L2ToL1Messenger.sol
  crates/l2/contracts/src/l2/interfaces/IL2ToL1Messenger.sol
  crates/l2/networking/rpc/l2/l1_message.rs
  crates/l2/networking/rpc/utils.rs
  crates/l2/prover/zkvm/interface/sp1/Cargo.lock
  crates/l2/prover/zkvm/interface/src/execution.rs
  crates/l2/sdk/src/merkle_tree.rs
  crates/l2/sdk/src/sdk.rs
  crates/l2/sequencer/errors.rs
  crates/l2/sequencer/l1_committer.rs
  crates/l2/tee/quote-gen/Cargo.lock
  crates/networking/rpc/clients/eth/mod.rs
  fixtures/genesis/l2.json
Labels: L2

#3407 feat(l2): burn gas when sending privileged transactions
  crates/l2/contracts/src/l1/CommonBridge.sol
  crates/l2/tests/tests.rs
Labels: L2

#3374 feat(l2): implement batch endpoint
  cmd/ethrex/l2/command.rs
  crates/common/types/batch.rs
  crates/l2/based/block_fetcher.rs
  crates/l2/networking/rpc/l2/batch.rs
  crates/l2/networking/rpc/l2/mod.rs
  crates/l2/networking/rpc/rpc.rs
  crates/l2/sequencer/l1_committer.rs
  crates/l2/sequencer/l1_proof_sender.rs
  crates/l2/sequencer/l1_proof_verifier.rs
  crates/l2/storage/src/api.rs
  crates/l2/storage/src/store.rs
  crates/l2/storage/src/store_db/in_memory.rs
  crates/l2/storage/src/store_db/libmdbx.rs
  crates/l2/storage/src/store_db/redb.rs
  crates/l2/storage/src/store_db/sql.rs
Labels: L2

#3310 chore(l1,levm): improve eest consume tests report and add Makefile
  .github/workflows/common_hive_reports.yaml
  Makefile
  crates/vm/levm/src/errors.rs
  tooling/hive_report/src/main.rs
Labels: ef-tests, levm

#3386 perf(levm): use a stack pool
  CHANGELOG.md
  crates/vm/levm/src/call_frame.rs
  crates/vm/levm/src/opcode_handlers/system.rs
  crates/vm/levm/src/vm.rs
Labels: performance

#3461 chore(l2): change print contract license
  fixtures/contracts/levm_print/Print.sol
Labels: L2

#3430 refactor(l2): replace replay rpc module with EthClient
  Cargo.lock
  cmd/ethrex/l2/command.rs
  cmd/ethrex_replay/Cargo.toml
  cmd/ethrex_replay/src/cli.rs
  cmd/ethrex_replay/src/fetcher.rs
  cmd/ethrex_replay/src/main.rs
  cmd/ethrex_replay/src/rpc/mod.rs
  cmd/ethrex_replay/src/run.rs
  crates/common/types/block_execution_witness.rs
  crates/common/utils.rs
  crates/l2/contracts/bin/deployer/main.rs
  crates/l2/sequencer/l1_committer.rs
  crates/l2/tests/state_reconstruct.rs
  crates/l2/tests/tests.rs
  crates/networking/rpc/clients/eth/errors.rs
  crates/networking/rpc/clients/eth/eth_sender.rs
  crates/networking/rpc/clients/eth/mod.rs
  crates/networking/rpc/types/block_identifier.rs
  tooling/load_test/src/main.rs
Labels: L2

#3471 ci(l2): increase commit time in sp1 integration test
  .github/workflows/main_prover.yaml
  crates/l2/docker-compose-l2.yaml
Labels: L2

#3441 refactor(l2): remove l2 txhash from L1Message
  crates/l2/based/block_fetcher.rs
  crates/l2/common/src/l1_messages.rs
  crates/l2/common/src/state_diff.rs
  crates/l2/contracts/src/l1/CommonBridge.sol
  crates/l2/contracts/src/l1/interfaces/ICommonBridge.sol
  crates/l2/networking/rpc/l2/l1_message.rs
  crates/l2/prover/zkvm/interface/src/execution.rs
  crates/l2/sdk/src/sdk.rs
  crates/l2/sequencer/block_producer/payload_builder.rs
  crates/l2/sequencer/l1_committer.rs
  crates/l2/tests/tests.rs
Labels: L2

#3403 docs(l2): update bridge docs
  docs/l2/deposits.md
  docs/l2/withdrawals.md
Labels: L2

#3453 feat(l2): implement `EthClient::get_batch_by_number`
  crates/common/types/batch.rs
  crates/networking/rpc/clients/eth/errors.rs
  crates/networking/rpc/clients/eth/mod.rs
Labels: L2

#3381 refactor(core): remove l2 feature from `cmd/ethrex` achieving a single binary for both L1 and L2
  .github/workflows/pr-main_l2_tdx.yaml
  cmd/ethrex/Cargo.toml
  cmd/ethrex/cli.rs
  cmd/ethrex/l2/command.rs
  cmd/ethrex/lib.rs
  cmd/ethrex/utils.rs
  crates/l2/Dockerfile
  crates/l2/Makefile
  crates/l2/tee/quote-gen/Cargo.toml
  docs/l1/dev-setup-l1.md
Labels: L2, cli, L1, simplification

#3464 ci(l2): ethrex replay risc0
  .github/workflows/main_prover_l1.yaml
  cmd/ethrex_replay/Makefile
  crates/l2/prover/src/backends/risc0.rs
  crates/l2/prover/zkvm/interface/risc0/src/main.rs
Labels: L2

#3415 test(l1): fix EEST RLP tests
  cmd/ethrex/cli.rs
Labels: ef-tests, L1

#3484 ci(core): fix block benchmark ci
  cmd/ethrex/bench/import_blocks_benchmark.rs
Labels: ci

#3483 fix(l2): gas used in replay block range
  cmd/ethrex_replay/src/cli.rs
  cmd/ethrex_replay/src/fetcher.rs
Labels: L2

#3413 feat(l1): embed dev-mode genesis in binary
  README.md
  cmd/ethrex/cli.rs
  cmd/ethrex/initializers.rs
  cmd/ethrex/networks.rs
  docs/l1/dev-setup-l1.md
  install.sh
Labels: L1

#3488 chore(l2): remove leftover l2 feature flag references
  .github/workflows/tag_l2_release.yaml
  crates/l2/Makefile
  crates/l2/based/README.md
  docs/l2/sequencer.md
Labels: L2

#3431 ci(core): create release when pushing a semver tag
  .github/workflows/tag_l2_release.yaml
  .github/workflows/tag_release.yaml
  cmd/ethrex/initializers.rs
  crates/l2/prover/zkvm/interface/build.rs
Labels: L2, L1, ci

#3490 chore(levm): improve beacon_root_contract_call readibility
  crates/vm/backends/levm/mod.rs
  crates/vm/backends/revm/mod.rs
Labels: levm

#3501 ci(l2): comment out slack notification on risc0 replay job because of timeouts
  .github/workflows/main_prover_l1.yaml
Labels: L2

#3506 fix(l2): revert to rust 1.87
  .github/workflows/pr_perf_levm.yaml
  .tool-versions
  Dockerfile
  crates/blockchain/dev/Dockerfile
  crates/l2/Dockerfile
  crates/l2/contracts/Dockerfile
  crates/vm/backends/revm/mod.rs
  docs/l1/dev-setup-l1.md
  rust-toolchain.toml
Labels: L2

#3470 fix(l1): metrics exporter dashboard total peer count panel
  crates/networking/p2p/peer_handler.rs
  crates/networking/rpc/net/mod.rs
  crates/networking/rpc/rpc.rs
Labels: L1

#3543 fix(l1): ignore unknown protocols in capability exchange
  crates/networking/p2p/rlpx/connection/server.rs
  crates/networking/p2p/rlpx/p2p.rs
  crates/networking/rpc/admin/peers.rs
Labels: L2, L1

#3570 fix(l2): use github token to avoid rate limit
  .github/workflows/pr-main_l2.yaml
  .github/workflows/pr-main_l2_contracts.yaml
  .github/workflows/pr-main_l2_tdx.yaml
  .github/workflows/pr-main_levm.yaml
  .github/workflows/pr_perf_levm.yaml
Labels: L2

#3542 ci(l1): comment flaky devp2p test BasicFindnode
  .github/workflows/pr-main_l1.yaml
Labels: L1, ci

#3555 perf(levm): improve sstore
  CHANGELOG.md
  crates/vm/levm/src/db/gen_db.rs
  crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs
Labels: performance, levm

#3554 fix(l2): seal a batch in a single DB transaction
  crates/l2/storage/src/api.rs
  crates/l2/storage/src/error.rs
  crates/l2/storage/src/store.rs
  crates/l2/storage/src/store_db/in_memory.rs
  crates/l2/storage/src/store_db/libmdbx.rs
  crates/l2/storage/src/store_db/redb.rs
  crates/l2/storage/src/store_db/sql.rs
Labels: L2, sequencer

#3503 perf(levm): improve blake2f
  CHANGELOG.md
  Makefile
  crates/vm/levm/src/precompiles.rs
Labels: performance

#3577 refactor(l2): move signer and signing functions into l2
  Cargo.lock
  Cargo.toml
  cmd/ethrex/bench/build_block_benchmark.rs
  cmd/ethrex/l2/options.rs
  crates/common/Cargo.toml
  crates/common/types/mod.rs
  crates/common/types/signer.rs
  crates/common/types/transaction.rs
  crates/l2/Cargo.toml
  crates/l2/contracts/Cargo.toml
  crates/l2/contracts/bin/deployer/main.rs
  crates/l2/docker-compose-l2-web3signer.yaml
  crates/l2/networking/rpc/Cargo.toml
  crates/l2/networking/rpc/clients.rs
  crates/l2/networking/rpc/l2/transaction.rs
  crates/l2/networking/rpc/lib.rs
  crates/l2/networking/rpc/signer.rs
  crates/l2/prover/zkvm/interface/sp1/Cargo.lock
  crates/l2/sdk/Cargo.toml
  crates/l2/sdk/src/l1_to_l2_tx_data.rs
  crates/l2/sdk/src/sdk.rs
  crates/l2/sequencer/configs.rs
  crates/l2/sequencer/errors.rs
  crates/l2/sequencer/l1_committer.rs
  crates/l2/sequencer/l1_proof_sender.rs
  crates/l2/sequencer/l1_proof_verifier.rs
  crates/l2/sequencer/setup.rs
  crates/l2/sequencer/utils.rs
  crates/l2/tee/quote-gen/Cargo.lock
  crates/l2/tests/tests.rs
  crates/networking/rpc/clients/eth/errors.rs
  crates/networking/rpc/clients/eth/eth_sender.rs
  crates/networking/rpc/clients/eth/mod.rs
  crates/web3signer/Cargo.toml
  crates/web3signer/web3signer.rs
  fixtures/keys/web3signer-key.yml
  tooling/load_test/Cargo.toml
  tooling/load_test/src/main.rs
Labels: L2

#3591 ci(l1, l2): create reusable step to install rust
  .github/actions/setup-rust/action.yml
  .github/workflows/common_hive_reports.yaml
  .github/workflows/daily_loc.yaml
  .github/workflows/main_flamegraph_report.yaml
  .github/workflows/main_perf_blocks_exec.yml
  .github/workflows/main_prover.yaml
  .github/workflows/main_prover_l1.yaml
  .github/workflows/pr-main_l1.yaml
  .github/workflows/pr-main_l2.yaml
  .github/workflows/pr-main_l2_contracts.yaml
  .github/workflows/pr-main_l2_tdx.yaml
  .github/workflows/pr-main_levm.yaml
  .github/workflows/pr_lint_readme.yaml
  .github/workflows/pr_loc.yaml
  .github/workflows/pr_perf_blocks_exec.yaml
  .github/workflows/pr_perf_build_block_bench.yml
  .github/workflows/pr_perf_levm.yaml
  .github/workflows/pr_perf_trie.yml
Labels: L2

#3607 feat(l2): monitor handle panics
  crates/l2/monitor/app.rs
  crates/l2/monitor/mod.rs
  crates/l2/monitor/utils.rs
  crates/l2/monitor/widget/batches.rs
  crates/l2/monitor/widget/blocks.rs
  crates/l2/monitor/widget/l1_to_l2_messages.rs
  crates/l2/monitor/widget/l2_to_l1_messages.rs
  crates/l2/sequencer/errors.rs
Labels: L2

#3498 docs(l2): improve ethrex-replay docs
  cmd/ethrex_replay/Makefile
  cmd/ethrex_replay/README.md
  cmd/ethrex_replay/src/cli.rs
  docs/ethrex_replay/ethrex_replay.md
Labels: L2

#3632 fix(l2): p2p 2 rlpx test ipv6
  crates/networking/p2p_2/rlpx/connection/handshake.rs
  crates/networking/p2p_2/types.rs
Labels: L2

#3617 fix(levm): ignore DB storage values for destroyed accounts
  crates/vm/levm/src/db/gen_db.rs
Labels: levm

#3637 fix(l2): panic because of double init tracing
  cmd/ethrex/cli.rs
  cmd/ethrex/ethrex.rs
Labels: L2

#3443 feat(l2): embed proxy contract in the SDK
  .github/workflows/pr-main_l1.yaml
  .github/workflows/pr-main_l2.yaml
  .github/workflows/pr-main_l2_prover.yaml
  Cargo.lock
  Cargo.toml
  Dockerfile
  crates/blockchain/dev/Dockerfile
  crates/l2/Dockerfile
  crates/l2/contracts/Dockerfile
  crates/l2/contracts/bin/deployer/main.rs
  crates/l2/sdk/Cargo.toml
  crates/l2/sdk/build.rs
  crates/l2/sdk/contract_utils/Cargo.toml
  crates/l2/sdk/contract_utils/src/compile.rs
  crates/l2/sdk/contract_utils/src/deps.rs
  crates/l2/sdk/contract_utils/src/lib.rs
  crates/l2/sdk/src/sdk.rs
  crates/l2/tee/quote-gen/service.nix
  crates/l2/tests/tests.rs
  fixtures/genesis/l2.json
Labels: L2

#3659 fix(l1): set base fee per gas only if we're past London hardfork
  cmd/ethrex/networks.rs
  crates/common/types/genesis.rs
Labels: L1

#3611 feat(l2): monitor handle index slicing
  crates/l2/monitor/app.rs
  crates/l2/monitor/mod.rs
  crates/l2/monitor/widget/l2_to_l1_messages.rs
  crates/l2/sequencer/errors.rs
Labels: L2

#3622 feat(l2): make monitor quit
  cmd/ethrex/l2/command.rs
  crates/l2/sequencer/mod.rs
Labels: L2

#3665 feat(l2): make contract compilation in the SDK optional
  .github/workflows/main_flamegraph_report.yaml
  .github/workflows/main_perf_blocks_exec.yml
  .github/workflows/pr-main_l1.yaml
  .github/workflows/pr-main_l2.yaml
  .github/workflows/pr-main_l2_prover.yaml
  .github/workflows/pr_lint_readme.yaml
  .github/workflows/pr_perf_blocks_exec.yaml
  .github/workflows/pr_perf_build_block_bench.yml
  Dockerfile
  crates/blockchain/dev/Dockerfile
  crates/l2/Dockerfile
  crates/l2/Makefile
  crates/l2/based/README.md
  crates/l2/contracts/Dockerfile
  crates/l2/sdk/build.rs
  crates/l2/sdk/src/sdk.rs
  crates/l2/tee/quote-gen/service.nix
  docs/l2/aligned_mode.md
  docs/l2/getting_started.md
  fixtures/genesis/l2.json
Labels: L2

#3661 ci(l1): support multiple hive versions depending on simulation.
  .github/workflows/pr-main_l1.yaml
Labels: L1

#3564 perf(levm): new memory model
  CHANGELOG.md
  crates/vm/levm/Cargo.toml
  crates/vm/levm/bench/revm_comparison/src/levm_bench.rs
  crates/vm/levm/src/call_frame.rs
  crates/vm/levm/src/execution_handlers.rs
  crates/vm/levm/src/memory.rs
  crates/vm/levm/src/opcode_handlers/environment.rs
  crates/vm/levm/src/opcode_handlers/keccak.rs
  crates/vm/levm/src/opcode_handlers/logging.rs
  crates/vm/levm/src/opcode_handlers/push.rs
  crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs
  crates/vm/levm/src/opcode_handlers/system.rs
  crates/vm/levm/src/vm.rs
Labels: performance, levm

#3680 fix(l2): `get_batch` failing if in validium mode
  crates/l2/storage/src/store.rs
Labels: L2

#3657 perf(levm): improve sstore perfomance further
  CHANGELOG.md
  cmd/ef_tests/state/report.rs
  cmd/ef_tests/state/runner/mod.rs
  cmd/ef_tests/state/runner/revm_runner.rs
  crates/common/types/account.rs
  crates/common/types/account_update.rs
  crates/common/utils.rs
  crates/storage/store_db/libmdbx.rs
  crates/vm/backends/levm/db.rs
  crates/vm/backends/levm/mod.rs
  crates/vm/levm/bench/revm_comparison/src/levm_bench.rs
  crates/vm/levm/src/call_frame.rs
  crates/vm/levm/src/db/gen_db.rs
  crates/vm/levm/src/db/mod.rs
  crates/vm/levm/src/memory.rs
  crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs
  crates/vm/levm/src/utils.rs
  crates/vm/levm/src/vm.rs
Labels: performance

#3346 refactor(l1, l2): metrics folder
  Dockerfile
  crates/l2/Makefile
  metrics/README.md
  metrics/docker-compose-metrics-alerts.overrides.yaml
  metrics/docker-compose-metrics-l1.overrides.yaml
  metrics/docker-compose-metrics-l2.overrides.yaml
  metrics/docker-compose-metrics.yaml
  metrics/provisioning/grafana_provisioning/alerting/alerts.json
  metrics/provisioning/grafana_provisioning/alerting/contact_points.json
  metrics/provisioning/grafana_provisioning/dashboards/common_dashboards/ethereum_metrics_exporter.json
  metrics/provisioning/grafana_provisioning/dashboards/common_dashboards/ethrex_l1_perf.json
  metrics/provisioning/grafana_provisioning/dashboards/common_dashboards/tx_dashboard.json
  metrics/provisioning/grafana_provisioning/dashboards/dashboard.yaml
  metrics/provisioning/grafana_provisioning/dashboards/dashboard_config_l1.yaml
  metrics/provisioning/grafana_provisioning/dashboards/dashboard_config_l2.yaml
  metrics/provisioning/grafana_provisioning/dashboards/l2_dashboards/l2_overview.json
  metrics/provisioning/grafana_provisioning/datasources/l1-rpc.yaml
  metrics/provisioning/grafana_provisioning/datasources/prometheus.yaml
  metrics/provisioning/prometheus/prometheus_l1_dev.yaml
  metrics/provisioning/prometheus/prometheus_l1_sync_docker.yaml
  metrics/provisioning/prometheus/prometheus_l2.yaml
  tooling/sync/Makefile
Labels: L2, L1

#3571 fix(l1): remove "p2p" capability from supported capabilities list
  crates/networking/p2p/rlpx/connection/server.rs
  crates/networking/p2p/rlpx/p2p.rs
  crates/networking/rpc/admin/peers.rs
Labels: p2p, L1

#3599 fix(l2): tdx to L2 prover client communication
  .github/workflows/pr-main_l2_tdx.yaml
  Cargo.lock
  crates/l2/build.rs
  crates/l2/prover/Cargo.toml
  crates/l2/prover/build.rs
  crates/l2/tee/quote-gen/Cargo.toml
  crates/l2/tee/quote-gen/Makefile
  crates/l2/tee/quote-gen/build.rs
  crates/l2/tee/quote-gen/image.nix
  crates/l2/tee/quote-gen/service.nix
Labels: L2, prover

#3718 ci(l1): fix assertoor tests
  .github/config/assertoor/network_params_blob.yaml
  .github/config/assertoor/network_params_ethrex_multiple_cl.yaml
  .github/config/assertoor/network_params_tx.yaml
  .github/workflows/pr-main_l1.yaml
Labels: L1

#3504 refactor(l1): replace rlpx listener functions with `spawned` implementation
  Cargo.toml
  crates/l2/tee/quote-gen/Cargo.lock
  crates/l2/tee/quote-gen/service.nix
  crates/networking/p2p/rlpx/connection/server.rs
Labels: L1

#3729 chore(l1): move network_params_ethrex_only.yaml to the fixtures folder
  Makefile
Labels: L1

#3734 fix(l2): estimate gas in call_to_contract_with_deposit
  crates/l2/tests/tests.rs
Labels: L2

#3673 refactor(l2): use modifier for pushing sequencers
  crates/l2/contracts/src/l1/based/SequencerRegistry.sol
Labels: L2, based

#3752 refactor(l2): remove blockByNumber
  crates/networking/rpc/clients/eth/mod.rs
Labels: L2

#3592 fix(levm): preemptively resize memory before executing call
  cmd/ef_tests/state/README.md
  crates/vm/levm/src/opcode_handlers/system.rs
Labels: levm

#3722 chore(levm): parallelize parsing ef state tests
  Cargo.lock
  Cargo.toml
  cmd/ef_tests/state/Cargo.toml
  cmd/ef_tests/state/parser.rs
  crates/common/Cargo.toml
Labels: levm

#3687 feat(l2): verify peer can handle l2 messages
  crates/networking/p2p/rlpx/connection/server.rs
Labels: p2p, L2, based

#3642 refactor(levm): rewrite of state EF tests runner first iteration
  .gitignore
  cmd/ef_tests/state/Cargo.toml
  cmd/ef_tests/state/Makefile
  cmd/ef_tests/state/lib.rs
  cmd/ef_tests/state/runner_v2/deserialize.rs
  cmd/ef_tests/state/runner_v2/error.rs
  cmd/ef_tests/state/runner_v2/mod.rs
  cmd/ef_tests/state/runner_v2/parser.rs
  cmd/ef_tests/state/runner_v2/result_check.rs
  cmd/ef_tests/state/runner_v2/run.rs
  cmd/ef_tests/state/runner_v2/runner.rs
  cmd/ef_tests/state/runner_v2/types.rs
  cmd/ef_tests/state/runner_v2/utils.rs
Labels: levm

#3747 fix(l2): fix L1 proof sender's wallet/signer
  crates/l2/networking/rpc/signer.rs
  crates/l2/sequencer/l1_proof_sender.rs
Labels: L2

#3691 fix(l2): enable bls12_381,k256 & ecdsa sp1 precompiles
  crates/l2/prover/zkvm/interface/sp1/Cargo.lock
  crates/l2/prover/zkvm/interface/sp1/Cargo.toml
Labels: tech debt, L2, prover

#2999 feat(l2): based P2P
  Cargo.lock
  cmd/ethrex/ethrex.rs
  cmd/ethrex/initializers.rs
  cmd/ethrex/l2/command.rs
  cmd/ethrex/l2/options.rs
  crates/blockchain/blockchain.rs
  crates/common/types/batch.rs
  crates/common/types/transaction.rs
  crates/l2/based/README.md
  crates/l2/based/block_fetcher.rs
  crates/l2/based/sequencer_state.rs
  crates/l2/based/state_updater.rs
  crates/l2/contracts/src/l1/based/OnChainProposer.sol
  crates/l2/contracts/src/l1/based/SequencerRegistry.sol
  crates/l2/contracts/src/l1/interfaces/ISequencerRegistry.sol
  crates/l2/monitor/app.rs
  crates/l2/sequencer/configs.rs
  crates/l2/sequencer/l1_committer.rs
  crates/l2/sequencer/mod.rs
  crates/l2/storage/src/api.rs
  crates/l2/storage/src/store.rs
  crates/l2/storage/src/store_db/in_memory.rs
  crates/l2/storage/src/store_db/libmdbx.rs
  crates/l2/storage/src/store_db/redb.rs
  crates/l2/storage/src/store_db/sql.rs
  crates/networking/p2p/Cargo.toml
  crates/networking/p2p/discv4/server.rs
  crates/networking/p2p/network.rs
  crates/networking/p2p/rlpx.rs
  crates/networking/p2p/rlpx/based.rs
  crates/networking/p2p/rlpx/connection/handshake.rs
  crates/networking/p2p/rlpx/connection/server.rs
  crates/networking/p2p/rlpx/error.rs
  crates/networking/p2p/rlpx/l2/l2_connection.rs
  crates/networking/p2p/rlpx/l2/messages.rs
  crates/networking/p2p/rlpx/l2/mod.rs
  crates/networking/p2p/rlpx/message.rs
  crates/networking/p2p/rlpx/p2p.rs
  crates/networking/p2p/rlpx/utils.rs
  crates/storage/store_db/redb.rs
Labels: L2, based

#3767 chore(l1): change logs in hive to info by default
  .github/workflows/common_hive_reports.yaml
  .github/workflows/pr-main_l1.yaml
  Makefile
Labels: L1, ci, tooling

#3772 chore(l1): avoid running EF blockchain tests on `make test`
  .github/workflows/pr-main_l1.yaml
  Makefile
Labels: L1

#3781 fix(l2): join verifier task
  crates/l2/sequencer/mod.rs
Labels: L2

#3505 docs(l1): move install instructions to new section and embed script one-liner
  README.md
  docs/SUMMARY.md
  docs/getting-started/README.md
  docs/getting-started/installing.md
  docs/getting-started/running.md
  install.sh
Labels: docs

#3604 feat(l2): embed contracts in deployer and system_contracts_updater
  crates/l2/Makefile
  crates/l2/contracts/Cargo.toml
  crates/l2/contracts/bin/deployer/cli.rs
  crates/l2/contracts/bin/deployer/error.rs
  crates/l2/contracts/bin/deployer/main.rs
  crates/l2/contracts/bin/system_contracts_updater/cli.rs
  crates/l2/contracts/bin/system_contracts_updater/error.rs
  crates/l2/contracts/bin/system_contracts_updater/main.rs
  crates/l2/contracts/build.rs
  crates/l2/docker-compose-l2.yaml
  crates/l2/sdk/build.rs
  crates/l2/sdk/contract_utils/src/compile.rs
  crates/l2/sdk/contract_utils/src/deps.rs
  crates/l2/sdk/src/sdk.rs
  crates/l2/tests/tests.rs
  fixtures/genesis/l2.json
Labels: L2

#3757 feat(l2): enhance monitor performance
  crates/l2/monitor/widget/batches.rs
  crates/l2/sequencer/errors.rs
Labels: L2

#3764 ci(l1,l2): lines of code report
  .github/workflows/pr_loc.yaml
Labels: L2, L1, ci

#3737 chore(l2): bump sp1 version to 5.0.8
  .github/workflows/main_prover.yaml
  .github/workflows/main_prover_l1.yaml
  .github/workflows/pr-main_l2_prover.yaml
  .github/workflows/tag_release.yaml
  Cargo.lock
  crates/l2/prover/Cargo.toml
  crates/l2/prover/zkvm/interface/Cargo.toml
  crates/l2/prover/zkvm/interface/build.rs
  crates/l2/prover/zkvm/interface/sp1/Cargo.lock
  crates/l2/prover/zkvm/interface/sp1/Cargo.toml
  docs/ethrex_replay/ethrex_replay.md
  docs/l2/prover.md
Labels: tech debt, L2, prover

#3834 fix(levm): fix custom bytecode runner
  crates/vm/levm/runner/src/main.rs
Labels: levm

#3835 chore(l1,l2): rename `grafana_provisioning` folder to just `grafana`.
  Makefile
  metrics/docker-compose-metrics-alerts.overrides.yaml
  metrics/docker-compose-metrics-l1.overrides.yaml
  metrics/docker-compose-metrics-l2.overrides.yaml
  metrics/docker-compose-metrics.yaml
  metrics/provisioning/grafana/alerting/alerts.json
  metrics/provisioning/grafana/alerting/contact_points.json
  metrics/provisioning/grafana/dashboards/common_dashboards/ethereum_metrics_exporter.json
  metrics/provisioning/grafana/dashboards/common_dashboards/ethrex_l1_perf.json
  metrics/provisioning/grafana/dashboards/common_dashboards/tx_dashboard.json
  metrics/provisioning/grafana/dashboards/dashboard.yaml
  metrics/provisioning/grafana/dashboards/dashboard_config_l1.yaml
  metrics/provisioning/grafana/dashboards/dashboard_config_l2.yaml
  metrics/provisioning/grafana/dashboards/l2_dashboards/l2_overview.json
  metrics/provisioning/grafana/datasources/l1-rpc.yaml
  metrics/provisioning/grafana/datasources/prometheus.yaml
Labels: L2

#3833 ci(l1): add the posibility to pin execution-spec-test ref
  .github/workflows/common_hive_reports.yaml
Labels: L1

#3645 build(l1, l2): add files to .dockerignore
  .dockerignore
  .gitignore
  Dockerfile
Labels: L2

#3815 docs(l1, l2): fix broken links and reference to files
  crates/l2/based/README.md
  docs/developers/l2/load_tests.md
  docs/developers/quickstart.md
  docs/l1/dev-setup-l1.md
  docs/l2/based/contracts.md
  docs/l2/based/sequencer.md
  docs/networking/Sync.md
Labels: L2

#3841 fix(l1): change `ethrex/tooling/sync/readme.MD` to `README.md`
  tooling/sync/README.md
Labels: L1

#3666 refactor(levm): rewrite of EF state tests runner second iteration
  .gitignore
  cmd/ef_tests/state/runner_v2/error.rs
  cmd/ef_tests/state/runner_v2/mod.rs
  cmd/ef_tests/state/runner_v2/parser.rs
  cmd/ef_tests/state/runner_v2/report.rs
  cmd/ef_tests/state/runner_v2/result_check.rs
  cmd/ef_tests/state/runner_v2/run.rs
  cmd/ef_tests/state/runner_v2/runner.rs
  cmd/ef_tests/state/runner_v2/types.rs
  cmd/ef_tests/state/runner_v2/utils.rs
Labels: levm

#3851 fix(l2): integration tests
  .github/workflows/pr-main_l2.yaml
  crates/l2/sdk/src/l1_to_l2_tx_data.rs
  crates/l2/sdk/src/sdk.rs
  crates/l2/tests/tests.rs
  fixtures/genesis/l2.json
Labels: L2

#3807 feat(l2): store sp1 & risc0 vk encoded
  Cargo.lock
  crates/l2/contracts/bin/deployer/main.rs
  crates/l2/prover/zkvm/interface/Cargo.toml
  crates/l2/prover/zkvm/interface/build.rs
  crates/l2/prover/zkvm/interface/risc0/Cargo.lock
  crates/l2/prover/zkvm/interface/sp1/Cargo.lock
Labels: L2

#3865 perf(l1): add (sender,nonce)=>tx_hash mapping
  CHANGELOG.md
  crates/blockchain/mempool.rs
Labels: performance

#3889 fix(l1): use p2p's `sync-test` feature in crate's `sync-test` feature
  cmd/ethrex/Cargo.toml
Labels: L1

#3893 feat(l1): add specific error message when import is used with the wrong network
  cmd/ethrex/cli.rs
Labels: L1

#3759 feat(l2): always use monitor
  cmd/ethrex/l2/initializers.rs
  cmd/ethrex/l2/options.rs
Labels: L2

#3785 feat(l2): ethrex replay add metrics & logs
  Cargo.lock
  cmd/ethrex_replay/.gitignore
  cmd/ethrex_replay/Cargo.toml
  cmd/ethrex_replay/Makefile
  cmd/ethrex_replay/src/bench.rs
  cmd/ethrex_replay/src/fetcher.rs
  cmd/ethrex_replay/src/main.rs
  crates/l2/prover/Cargo.toml
  crates/l2/prover/src/backends/exec.rs
  crates/l2/prover/src/backends/risc0.rs
  crates/l2/prover/src/backends/sp1.rs
  docs/SUMMARY.md
  docs/ethrex_replay/profiling.md
Labels: tech debt, L2

#3910 fix(l2): update make target to init-l1-docker in tdx
  .github/workflows/pr-main_l2_tdx.yaml
  crates/l2/based/README.md
Labels: L2

#3902 refactor(l2): remove old dependencies from ethrex replay
  Cargo.lock
  cmd/ethrex_replay/Cargo.toml
  cmd/ethrex_replay/src/plot_composition.rs
Labels: L2

#3693 chore(l1): add snooper for ethrex on ethereum package network params
  Makefile
  fixtures/network/network_params.yaml
Labels: L1
