Repository lambdaclass/ethrex, pull requests merged in 2025-10, with the labels that each got.

#4689 perf(l1): snap sync optimizations
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  cmd/ethrex/Cargo.toml
  crates/common/trie/Cargo.toml
  crates/common/trie/db.rs
  crates/common/trie/nibbles.rs
  crates/common/trie/trie.rs
  crates/common/trie/trie_sorted.rs
  crates/concurrency/Cargo.lock
  crates/concurrency/Cargo.toml
  crates/concurrency/concurrency.rs
  crates/l2/prover/src/guest_program/src/risc0/Cargo.lock
  crates/l2/tee/quote-gen/Cargo.lock
  crates/networking/p2p/Cargo.toml
  crates/networking/p2p/network.rs
  crates/networking/p2p/peer_handler.rs
  crates/networking/p2p/sync.rs
  crates/networking/p2p/sync/code_collector.rs
  crates/networking/p2p/sync/state_healing.rs
  crates/networking/p2p/sync/storage_healing.rs
  crates/networking/p2p/utils.rs
  crates/storage/trie_db/rocksdb.rs
Labels: performance, L1

#4734 chore(l1, l2): revert snap sync optimizations PR
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  cmd/ethrex/Cargo.toml
  crates/common/trie/Cargo.toml
  crates/common/trie/db.rs
  crates/common/trie/nibbles.rs
  crates/common/trie/trie.rs
  crates/common/trie/trie_sorted.rs
  crates/concurrency/Cargo.lock
  crates/concurrency/Cargo.toml
  crates/concurrency/concurrency.rs
  crates/l2/prover/src/guest_program/src/risc0/Cargo.lock
  crates/l2/tee/quote-gen/Cargo.lock
  crates/networking/p2p/Cargo.toml
  crates/networking/p2p/network.rs
  crates/networking/p2p/peer_handler.rs
  crates/networking/p2p/sync.rs
  crates/networking/p2p/sync/code_collector.rs
  crates/networking/p2p/sync/state_healing.rs
  crates/networking/p2p/sync/storage_healing.rs
  crates/networking/p2p/utils.rs
  crates/storage/trie_db/rocksdb.rs
Labels: L2, L1

#4737 chore(l1, l2): remove `cfg-if` crate
  Cargo.lock
  Cargo.toml
  cmd/ethrex/Cargo.toml
  cmd/ethrex/initializers.rs
  cmd/ethrex/l2/command.rs
  cmd/ethrex/l2/initializers.rs
  crates/blockchain/Cargo.toml
  crates/l2/Cargo.toml
  crates/l2/prover/Cargo.toml
  crates/l2/prover/src/guest_program/src/risc0/Cargo.lock
  crates/l2/prover/src/guest_program/src/sp1/Cargo.lock
  crates/networking/rpc/Cargo.toml
  crates/vm/Cargo.toml
Labels: L2, L1

#4741 fix(levm): fix access list bug
  crates/vm/levm/src/vm.rs
Labels: levm

#4740 chore(l1): remove libmdbx
  Cargo.lock
  Cargo.toml
  cmd/ethrex/Cargo.toml
  cmd/ethrex/initializers.rs
  cmd/ethrex/l2/command.rs
  crates/common/trie/Cargo.toml
  crates/common/trie/node_hash.rs
  crates/storage/Cargo.toml
  crates/storage/error.rs
  crates/storage/lib.rs
  crates/storage/rlp.rs
  crates/storage/store.rs
  crates/storage/store_db/libmdbx.rs
  crates/storage/store_db/mod.rs
  crates/storage/store_db/rocksdb.rs
  crates/storage/trie_db/libmdbx.rs
  crates/storage/trie_db/libmdbx_dupsort.rs
  crates/storage/trie_db/libmdbx_dupsort_locked.rs
  crates/storage/trie_db/libmdbx_locked.rs
  crates/storage/trie_db/mod.rs
  crates/storage/trie_db/test_utils.rs
  crates/storage/trie_db/utils.rs
  docs/developers/installing.md
  tooling/sync/Makefile
Labels: L1

#4750 chore(l1): add validation status to snap sync slack notification
  tooling/sync/server_runner.py
Labels: L1

#4697 feat(l1,l2): add tooling to migrate from libmdbx to rocksdb
  Cargo.lock
  Cargo.toml
  tooling/migrations/Cargo.toml
  tooling/migrations/README.md
  tooling/migrations/src/cli.rs
  tooling/migrations/src/main.rs
  tooling/migrations/src/utils.rs
Labels: L2, L1

#4749 fix(l1): bump revm version on tooling/ef-tests/state crate
  tooling/ef_tests/state/Cargo.toml
  tooling/ef_tests/state/report.rs
  tooling/ef_tests/state/runner/mod.rs
  tooling/ef_tests/state/runner/revm_db.rs
  tooling/ef_tests/state/runner/revm_runner.rs
Labels: L1

#4739 fix(l2): set `l2 --dev` mempool size to non zero
  cmd/ethrex/cli.rs
Labels: L2

#4768 ci(l1, l2): add GitHub runner token to Install Protoc step
  .github/workflows/tag_release.yaml
Labels: L2, L1

#4774 ci(l1): update execution-spec-test to 5.1.0 in daily hive tests.
  .github/workflows/common_hive_reports.yaml
Labels: L1

#4773 chore(l1): remove unused temporary in snap_sync method
  crates/networking/p2p/sync.rs
Labels: L1

#4772 perf(l1): remove metric current_step string lock
  CHANGELOG.md
  crates/networking/p2p/metrics.rs
  crates/networking/p2p/network.rs
  crates/networking/p2p/peer_handler.rs
  crates/networking/p2p/sync.rs
  crates/networking/p2p/sync/state_healing.rs
  crates/networking/p2p/sync/storage_healing.rs
Labels: performance, L1

#4759 chore(l1, l2): removed clone when adding block to store
  cmd/ethrex/bench/build_block_benchmark.rs
  cmd/ethrex/cli.rs
  crates/blockchain/blockchain.rs
  crates/blockchain/smoke_test.rs
  crates/l2/based/block_fetcher.rs
  crates/l2/sequencer/block_producer.rs
  crates/networking/p2p/rlpx/l2/l2_connection.rs
  crates/networking/p2p/sync.rs
  crates/networking/rpc/engine/payload.rs
  tooling/ef_tests/blockchain/test_runner.rs
  tooling/ef_tests/state_v2/src/modules/block_runner.rs
  tooling/migrations/src/cli.rs
Labels: L2, L1

#4744 docs(l1): tradeoffs of transactional RocksDB modes
  docs/internal/l1/transactions_tradeoffs.md
Labels: L1

#4612 ci(l1): update hive runner to use `ethpandaops/hive-github-action`.
  .github/workflows/common_hive_reports.yaml
  .github/workflows/pr-main_l1.yaml
Labels: L1

#4789 ci(l1): use same configuration for daily hive jobs as in the hive page.
  .github/workflows/common_hive_reports.yaml
Labels: L1

#4765 refactor(l1): remove unneeded `add_transaction_location` & `add_transaction_locations` db methods
  crates/storage/api.rs
  crates/storage/store.rs
  crates/storage/store_db/in_memory.rs
  crates/storage/store_db/rocksdb.rs
Labels: L1

#4787 docs(l1, l2): update getting started to remove docker stuff and run installing binaries instead
  docs/SUMMARY.md
  docs/getting-started/README.md
  docs/getting-started/installation/binary_distribution.md
  docs/getting-started/installation/building_from_source.md
  docs/getting-started/installation/docker_images.md
  docs/getting-started/quickstart-l1.md
  docs/getting-started/quickstart-l2.md
  docs/l2/introduction.md
Labels: L2, L1
