Repository lambdaclass/ethrex, pull requests merged in 2025-09, with the labels that each got.

#4220 perf(levm): process JUMPDEST gas and pc together within the given JUMP/JUMPI opcode
  CHANGELOG.md
  crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs
Labels: performance

#4242 fix(l2): properly restore context in payload_builder
  crates/l2/sequencer/block_producer/payload_builder.rs
Labels: L2

#4188 feat(l1,levm): implement CLZ opcode
  crates/vm/levm/src/gas_cost.rs
  crates/vm/levm/src/opcode_handlers/arithmetic.rs
  crates/vm/levm/src/opcodes.rs
  tooling/ef_tests/blockchain/test_runner.rs
  tooling/ef_tests/state/runner/levm_runner.rs
Labels: L1

#3866 feat(l2): discard invalid batch proofs
  crates/l2/contracts/src/l1/OnChainProposer.sol
  crates/l2/contracts/src/l1/based/OnChainProposer.sol
  crates/l2/sequencer/l1_proof_sender.rs
  crates/l2/sequencer/l1_proof_verifier.rs
  crates/l2/storage/src/api.rs
  crates/l2/storage/src/store.rs
  crates/l2/storage/src/store_db/in_memory.rs
  crates/l2/storage/src/store_db/sql.rs
Labels: L2, prover

#4206 feat(levm): osaka modexp gas cost changes
  crates/vm/levm/src/errors.rs
  crates/vm/levm/src/gas_cost.rs
  crates/vm/levm/src/l2_precompiles.rs
  crates/vm/levm/src/opcode_handlers/system.rs
  crates/vm/levm/src/precompiles.rs
  crates/vm/levm/src/vm.rs
  crates/vm/levm/tests/tests.rs
  tooling/ef_tests/blockchain/test_runner.rs
  tooling/ef_tests/state/runner/levm_runner.rs
  tooling/ef_tests/state_v2/src/modules/runner.rs
Labels: levm

#4255 feat(l1): chunk bytecode downloads
  crates/networking/p2p/sync.rs
Labels: syncing

#4029 feat(l1): start building payloads as soon as we get an fcu
  cmd/ethrex/bench/build_block_benchmark.rs
  crates/blockchain/blockchain.rs
  crates/blockchain/error.rs
  crates/blockchain/payload.rs
  crates/common/types/payload.rs
  crates/networking/rpc/engine/fork_choice.rs
  crates/networking/rpc/engine/payload.rs
  crates/storage/api.rs
  crates/storage/rlp.rs
  crates/storage/store.rs
  crates/storage/store_db/in_memory.rs
  crates/storage/store_db/libmdbx.rs
Labels: L1

#4264 fix(l1, l2): use `BTreeMap` for `InMemoryTrieDB` and optimize stateless execution by avoiding state cloning
  .github/workflows/main_prover_l1.yaml
  .github/workflows/pr-main_l1.yaml
  Cargo.toml
  crates/blockchain/blockchain.rs
  crates/common/rkyv_utils.rs
  crates/common/trie/db.rs
  crates/common/trie/node_hash.rs
  crates/common/trie/trie.rs
  crates/common/types/block_execution_witness.rs
  crates/networking/rpc/debug/execution_witness.rs
  crates/storage/store_db/in_memory.rs
  fixtures/cache/rpc_prover/cache_hoodi_1130549.bin
  fixtures/cache/rpc_prover/cache_hoodi_1132599.bin
Labels: L2, L1, tooling

#4252 perf(levm): use x86-64-v2 cpu target on linux by default
  .cargo/config.toml
  CHANGELOG.md
  Dockerfile
Labels: performance

#4263 chore(l1): correct block time and gas used % y axis labels on grafana panel
  metrics/provisioning/grafana/dashboards/common_dashboards/ethrex_l1_perf.json
Labels: L1

#4269 chore(l1): remove old comments and code
  crates/networking/p2p/peer_handler.rs
  crates/networking/p2p/sync.rs
  crates/networking/p2p/sync/state_healing.rs
Labels: L1

#4229 fix(l1,l2): eth client support 4 byte signatures, return decoded error in `RpcErr::Revert`
  crates/networking/rpc/clients/eth/mod.rs
  crates/networking/rpc/utils.rs
Labels: rpc-api, L2, L1

#4283 fix(l2): grafana for macos
  metrics/docker-compose-metrics-l2.overrides.yaml
Labels: L2

#4042 fix(l2): remove empty account diffs from payload builder's blob size estimation
  crates/l2/common/src/state_diff.rs
  crates/l2/sequencer/block_producer/payload_builder.rs
  crates/l2/sequencer/errors.rs
  crates/l2/sequencer/l1_committer.rs
Labels: L2

#4034 feat(l1): print loaded chain config on startup (#4027)
  cmd/ethrex/initializers.rs
  cmd/ethrex/utils.rs
  crates/common/types/genesis.rs
Labels: L1

#3850 perf(levm): add an implementation of BLAKE2B that uses NEON
  CHANGELOG.md
  crates/common/crypto/blake2f/aarch64.rs
  crates/common/crypto/blake2f/mod.rs
Labels: performance

#4322 fix(l1): revert "perf(levm): add an implementation of BLAKE2B that uses NEON..."
  CHANGELOG.md
  crates/common/crypto/blake2f/aarch64.rs
  crates/common/crypto/blake2f/mod.rs
Labels: levm, L1

#4174 feat(l2): more metrics and upgraded dashboard
  crates/blockchain/metrics/l2/api.rs
  crates/blockchain/metrics/l2/metrics.rs
  crates/l2/sequencer/block_producer/payload_builder.rs
  crates/l2/sequencer/errors.rs
  crates/l2/sequencer/l1_committer.rs
  crates/l2/sequencer/l1_proof_sender.rs
  crates/l2/sequencer/proof_coordinator.rs
  metrics/provisioning/grafana/dashboards/l2_dashboards/l2_overview.json
Labels: L2

#4216 chore(l2): optimize execution of empty batches
  crates/blockchain/blockchain.rs
  crates/common/types/block_execution_witness.rs
  crates/l2/prover/src/guest_program/src/execution.rs
  crates/vm/witness_db.rs
Labels: L2

#4295 chore(l1): fix snap sync logs
  crates/networking/p2p/metrics.rs
  crates/networking/p2p/network.rs
  crates/networking/p2p/peer_handler.rs
  crates/networking/p2p/sync.rs
  crates/networking/p2p/sync/state_healing.rs
  crates/networking/p2p/sync/storage_healing.rs
Labels: L1, syncing

#4289 fix(l1, l2): hash every address once
  crates/blockchain/blockchain.rs
  crates/common/trie/trie.rs
  crates/common/trie/verify_range.rs
  crates/common/types/block_execution_witness.rs
  crates/l2/prover/src/guest_program/src/execution.rs
  crates/networking/rpc/debug/execution_witness.rs
  crates/storage/store.rs
  crates/storage/trie_db/libmdbx.rs
Labels: L2, L1, tooling

#4273 feat(l1, l2): print zkVM cycles of guest programs
  crates/l2/prover/src/guest_program/src/risc0/src/main.rs
  crates/l2/prover/src/guest_program/src/sp1/src/main.rs
Labels: L2, L1, prover

#4329 fix(l1): fixed update_pivot deadlock
  crates/networking/p2p/peer_handler.rs
Labels: L1

#4259 feat(l1): improve transaction broadcasting logic
  crates/blockchain/mempool.rs
  crates/networking/p2p/kademlia.rs
  crates/networking/p2p/rlpx/connection/handshake.rs
  crates/networking/p2p/rlpx/connection/server.rs
  crates/networking/p2p/tx_broadcaster.rs
Labels: L1

#4331 feat(l1): run with debug assert
  tooling/sync/Makefile
  tooling/sync/server_runner.py
Labels: L1

#4332 feat(l1): add max blobs per tx check (Osaka EIP-7594)
  crates/vm/levm/src/constants.rs
  crates/vm/levm/src/hooks/default_hook.rs
  tooling/ef_tests/blockchain/test_runner.rs
  tooling/ef_tests/state/runner/levm_runner.rs
  tooling/ef_tests/state_v2/src/modules/runner.rs
Labels: L1

#4305 feat(l2): revert batches improvements
  cmd/ethrex/l2/command.rs
Labels: L2

#4258 ci(l1,l2): add workflow to notify failed jobs in main.
  .github/scripts/notify_workflow_failure.sh
  .github/workflows/common_failure_alerts.yaml
Labels: L2

#4341 fix(l1): `ethrex_replay` temporary fix for block header hashes
  crates/blockchain/blockchain.rs
  crates/common/types/block_execution_witness.rs
Labels: L1

#4324 feat(l1,l2): enable log levels update in runtime
  Cargo.lock
  cmd/ethrex/cli.rs
  cmd/ethrex/ethrex.rs
  cmd/ethrex/initializers.rs
  cmd/ethrex/l2/command.rs
  cmd/ethrex/l2/initializers.rs
  crates/l2/networking/rpc/Cargo.toml
  crates/l2/networking/rpc/rpc.rs
  crates/networking/rpc/admin/mod.rs
  crates/networking/rpc/rpc.rs
  crates/networking/rpc/utils.rs
Labels: L2

#4345 ci(l1, l2): improve sending of slack messages to appropriate channels
  .github/scripts/notify_workflow_failure.sh
  .github/workflows/common_failure_alerts.yaml
Labels: L2, L1

#4292 feat(l1): p256 verify implementation on L1
  crates/vm/levm/Cargo.toml
  crates/vm/levm/src/constants.rs
  crates/vm/levm/src/gas_cost.rs
  crates/vm/levm/src/l2_precompiles.rs
  crates/vm/levm/src/lib.rs
  crates/vm/levm/src/opcode_handlers/system.rs
  crates/vm/levm/src/precompiles.rs
  crates/vm/levm/src/utils.rs
  crates/vm/levm/src/vm.rs
  crates/vm/levm/tests/p_256_verify.json
  crates/vm/levm/tests/tests.rs
  tooling/ef_tests/blockchain/test_runner.rs
  tooling/ef_tests/state/runner/levm_runner.rs
Labels: L1

#4385 fix(l1): fixed global storage slot metric
  crates/networking/p2p/sync/storage_healing.rs
Labels: L1

#4387 docs(l1,l2,levm): add contributing docs
  CONTRIBUTING.md
  README.md
Labels: levm, L2, L1

#4337 fix(l1, l2): remove trust assumptions from guest program inputs
  Cargo.lock
  cmd/ethrex_replay/src/cache.rs
  cmd/ethrex_replay/src/run.rs
  crates/blockchain/blockchain.rs
  crates/common/rkyv_utils.rs
  crates/common/types/block_execution_witness.rs
  crates/l2/prover/src/guest_program/Cargo.toml
  crates/l2/prover/src/guest_program/src/execution.rs
  crates/l2/prover/src/guest_program/src/input.rs
  crates/l2/prover/src/guest_program/src/risc0/Cargo.lock
  crates/l2/prover/src/guest_program/src/sp1/Cargo.lock
  crates/l2/sequencer/proof_coordinator.rs
  crates/l2/tee/quote-gen/Cargo.lock
  crates/networking/rpc/debug/execution_witness.rs
  crates/vm/lib.rs
  crates/vm/witness_db.rs
Labels: L2, L1

#4381 perf(levm): refactor substate backups
  CHANGELOG.md
  crates/vm/backends/levm/mod.rs
  crates/vm/levm/src/db/gen_db.rs
  crates/vm/levm/src/hooks/default_hook.rs
  crates/vm/levm/src/opcode_handlers/environment.rs
  crates/vm/levm/src/opcode_handlers/logging.rs
  crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs
  crates/vm/levm/src/opcode_handlers/system.rs
  crates/vm/levm/src/utils.rs
  crates/vm/levm/src/vm.rs
Labels: performance, levm

#4413 ci(l1): move replay job to a different workflow.
  .github/workflows/pr-main_l1.yaml
  .github/workflows/pr-main_replay.yaml
Labels: L1

#4429 chore(l1,l2): use IPs instead of localhost as default RPC address
  cmd/ethrex/cli.rs
  docs/CLI.md
Labels: L2, L1

#4399 fix(l1): handshake and codec panics
  crates/networking/p2p/rlpx/connection/codec.rs
  crates/networking/p2p/rlpx/connection/handshake.rs
Labels: L1

#4394 fix(l2): race condition tracking privileged tx count
  crates/l2/common/src/privileged_transactions.rs
  crates/l2/sequencer/block_producer.rs
  crates/l2/sequencer/block_producer/payload_builder.rs
  crates/l2/sequencer/l1_committer.rs
  crates/l2/storage/src/api.rs
  crates/l2/storage/src/store.rs
  crates/l2/storage/src/store_db/in_memory.rs
  crates/l2/storage/src/store_db/sql.rs
  crates/networking/rpc/utils.rs
  docs/l2/fundamentals/deposits.md
Labels: L2

#4479 perf(levm): fix block hash caching
  CHANGELOG.md
  crates/storage/store.rs
Labels: performance, levm

#4028 fix(l1): handle syncing in case of reorgs and handle the case of reorg with invalid side chain
  .github/workflows/pr-main_l1.yaml
  crates/blockchain/error.rs
  crates/networking/p2p/peer_handler.rs
  crates/networking/p2p/sync.rs
  tooling/ef_tests/blockchain/test_runner.rs
Labels: L1

#4441 ci(replay): add job on every pr for zkvm executing
  .github/workflows/pr-main_replay.yaml
  cmd/ethrex_replay/Makefile
Labels: replay

#4498 ci(l2): install latest rex version
  .github/workflows/pr-main_l2.yaml
Labels: L2

#4486 fix(l2): use empty SP1 elf when linting
  crates/l2/prover/src/backend/sp1.rs
Labels: L2

#4444 refactor(l1): moved peer scores into kademlia's PeerData
  cmd/ethrex/initializers.rs
  crates/networking/p2p/kademlia.rs
  crates/networking/p2p/network.rs
  crates/networking/p2p/p2p.rs
  crates/networking/p2p/peer_handler.rs
  crates/networking/p2p/peer_score.rs
  crates/networking/p2p/sync.rs
  crates/networking/p2p/sync/state_healing.rs
  crates/networking/p2p/sync/storage_healing.rs
Labels: L1

#4506 fix(l1): change default script branch in sync tool
  tooling/sync/Makefile
  tooling/sync/server_runner.py
Labels: L1

#4415 feat(l2): `/health` sequencer endpoint
  crates/l2/networking/rpc/signer.rs
  crates/l2/sequencer/admin_server.rs
  crates/l2/sequencer/block_producer.rs
  crates/l2/sequencer/l1_committer.rs
  crates/l2/sequencer/l1_proof_sender.rs
  crates/l2/sequencer/l1_watcher.rs
  crates/l2/sequencer/metrics.rs
  crates/l2/sequencer/mod.rs
  crates/networking/rpc/clients/eth/mod.rs
  docs/l2/admin.md
Labels: L2

#4267 feat(l2): add a configurable batch gas limit
  cmd/ethrex/l2/options.rs
  crates/l2/sequencer/configs.rs
  crates/l2/sequencer/errors.rs
  crates/l2/sequencer/l1_committer.rs
  crates/l2/sequencer/mod.rs
Labels: L2

#4515 fix(l1): remove second log level override from `init_tracing`
  cmd/ethrex/initializers.rs
Labels: L1

#4505 refactor(replay): merge block-range command with blocks
  cmd/ethrex_replay/src/cli.rs
Labels: replay

#4164 fix(l2): avoid blocking in `L1Committer`
  crates/l2/sequencer/l1_committer.rs
Labels: L2

#4402 feat(replay): add `--cache-level` flag in `ethrex-replay` to decide whether to write the cache or not
  cmd/ethrex_replay/src/cache.rs
  cmd/ethrex_replay/src/cli.rs
  cmd/ethrex_replay/src/fetcher.rs
  tooling/replayer/src/main.rs
Labels: tooling, replay

#4537 fix(l1): request storage peer leak
  crates/networking/p2p/kademlia.rs
  crates/networking/p2p/peer_handler.rs
  crates/networking/p2p/sync.rs
Labels: L1

#4546 feat(replay): allow replay in range from some block to the latest
  cmd/ethrex_replay/src/cli.rs
Labels: replay

#4532 docs(l1): discv4 send neighbors chunk size comment
  crates/networking/p2p/discv4/server.rs
Labels: L1

#4301 feat(l1): added the allocator jemalloc
  CHANGELOG.md
  Cargo.lock
  cmd/ethrex/Cargo.toml
  cmd/ethrex/ethrex.rs
  cmd/ethrex_replay/Cargo.toml
  cmd/ethrex_replay/src/main.rs
  crates/networking/rpc/Cargo.toml
  crates/networking/rpc/rpc.rs
Labels: L1

#4490 feat(l1): make rocksdb the default database
  cmd/ethrex/Cargo.toml
  cmd/ethrex/bench/build_block_benchmark.rs
  cmd/ethrex/l2/command.rs
  crates/storage/rlp.rs
  crates/storage/store_db/libmdbx.rs
  crates/storage/store_db/rocksdb.rs
Labels: L1

#4572 feat(l1): validate bytecodes at snap sync end
  crates/networking/p2p/sync.rs
Labels: L1

#4547 fix(l2): properly update message hashes in committer
  .github/workflows/main_prover.yaml
  .github/workflows/main_prover_l1.yaml
  crates/l2/sequencer/l1_committer.rs
  crates/l2/sequencer/l1_proof_sender.rs
  crates/l2/tests/tests.rs
Labels: L2

#4487 perf(l1): save code hash during account insertion and state healing
  CHANGELOG.md
  crates/networking/p2p/sync.rs
  crates/networking/p2p/sync/code_collector.rs
  crates/networking/p2p/sync/state_healing.rs
  crates/networking/p2p/utils.rs
Labels: performance, L1

#4484 feat(l1): update EEST to version 5.0
  tooling/ef_tests/blockchain/.fixtures_url
  tooling/ef_tests/blockchain/deserialize.rs
  tooling/ef_tests/blockchain/network.rs
  tooling/ef_tests/blockchain/tests/all.rs
  tooling/ef_tests/state/.fixtures_url
  tooling/ef_tests/state/parser.rs
Labels: L1

#4380 ci(l1): update daily Hive job to use execution-spec-tests@v5.0.0
  .github/workflows/common_hive_reports.yaml
  .github/workflows/daily_hive_report.yaml
  .github/workflows/daily_loc_report.yaml
  .github/workflows/pr-main_l1.yaml
  tooling/hive_report/src/main.rs
Labels: L1

#4578 chore(l1): improve engine API logs
  crates/networking/p2p/sync.rs
  crates/networking/rpc/engine/payload.rs
  crates/networking/rpc/types/payload.rs
Labels: L1

#4500 perf(levm): refactor `bls12_g1add` to use lambdaworks
  CHANGELOG.md
  crates/vm/levm/src/precompiles.rs
Labels: performance, levm

#4548 feat(replay): support public L2 networks blocks/batches replay
  .github/workflows/main_prover_l1.yaml
  .github/workflows/pr-main_replay.yaml
  cmd/ethrex_replay/src/cache.rs
  cmd/ethrex_replay/src/cli.rs
  cmd/ethrex_replay/src/fetcher.rs
  cmd/ethrex_replay/src/lib.rs
  cmd/ethrex_replay/src/run.rs
  crates/common/config/networks.rs
  crates/l2/sequencer/block_producer.rs
  fixtures/cache/rpc_prover/cache_hoodi_1219705.json
  fixtures/cache/rpc_prover/cache_hoodi_1265656.json
Labels: replay

#4627 refactor(levm): improve ecrecover
  crates/vm/levm/src/precompiles.rs
Labels: levm

#4630 chore(l1): fix memory spike when transitioning from snap to fullsync
  crates/networking/p2p/sync.rs
Labels: L1

#4626 ci(l1): set --docker.output for running hive tests in ci
  .github/workflows/pr-main_l1.yaml
Labels: L1

#4647 ci(l1,l2): free unused packages on github runners
  .github/workflows/pr-main_l1.yaml
  .github/workflows/pr-main_l2_prover.yaml
Labels: L2, L1

#4616 fix(replay): fix execution with eth_getProof
  cmd/ethrex_replay/src/cli.rs
  cmd/ethrex_replay/src/helpers.rs
  cmd/ethrex_replay/src/lib.rs
  cmd/ethrex_replay/src/rpc/db.rs
  crates/common/trie/Cargo.toml
  crates/common/trie/node/branch.rs
Labels: replay

#4599 fix(l1): use transactional database with RocksDB
  crates/storage/store_db/rocksdb.rs
  crates/storage/trie_db/rocksdb.rs
  crates/storage/trie_db/rocksdb_locked.rs
Labels: L1

#4615 refactor(l1): mempool locks
  crates/blockchain/mempool.rs
  crates/networking/p2p/tx_broadcaster.rs
Labels: L1

#4620 test(l1): add reorg testing framework
  .github/workflows/pr-main_l1.yaml
  .gitignore
  Cargo.lock
  Cargo.toml
  cmd/ethrex/cli.rs
  crates/networking/rpc/types/fork_choice.rs
  crates/networking/rpc/types/payload.rs
  tooling/reorgs/Cargo.toml
  tooling/reorgs/README.md
  tooling/reorgs/src/main.rs
  tooling/reorgs/src/simulator.rs
Labels: L1

#4641 refactor(replay): `ethrex-replay` improvements
  cmd/ethrex_replay/Makefile
  cmd/ethrex_replay/src/bench.rs
  cmd/ethrex_replay/src/block_run_report.rs
  cmd/ethrex_replay/src/cli.rs
  cmd/ethrex_replay/src/lib.rs
  cmd/ethrex_replay/src/report.rs
  cmd/ethrex_replay/src/run.rs
  cmd/ethrex_replay/src/slack.rs
  docs/ethrex_replay/ethrex_replay.md
  tooling/replayer/src/main.rs
Labels: replay

#4643 chore(l1): update genesis files to include Fusaka fields
  cmd/ethrex/networks/holesky/genesis.json
  cmd/ethrex/networks/hoodi/genesis.json
  cmd/ethrex/networks/mainnet/genesis.json
  cmd/ethrex/networks/sepolia/genesis.json
  crates/common/types/fork_id.rs
  crates/common/types/genesis.rs
  crates/networking/rpc/rpc.rs
  crates/vm/backends/revm/helpers.rs
  tooling/ef_tests/blockchain/types.rs
Labels: L1

#4656 feat(l1): use descriptive error when we fail to replace a mempool tx
  crates/blockchain/error.rs
  crates/blockchain/mempool.rs
Labels: L1

#4638 refactor(l1): enhance mempool oldest removal
  crates/blockchain/mempool.rs
Labels: L1

#4671 ci(l2): free space in lint workflow
  .github/workflows/pr-main_l2.yaml
Labels: L2

#4677 docs(l1): add CLI reference links in L1 startup docs
  docs/l1/running/configuration.md
  docs/l1/running/startup.md
  docs/l2/running.md
Labels: docs, L1

#4613 fix(replay): block number wrongly displayed in RpcDB
  cmd/ethrex_replay/src/fetcher.rs
  cmd/ethrex_replay/src/rpc/db.rs
Labels: replay

#4683 fix(replay): bring back CI benches
  .github/workflows/pr-main_replay.yaml
  cmd/ethrex_replay/Cargo.toml
  cmd/ethrex_replay/Makefile
  cmd/ethrex_replay/src/cli.rs
  cmd/ethrex_replay/src/report.rs
  tooling/replayer/Cargo.toml
  tooling/replayer/src/main.rs
Labels: replay

#4678 feat(l2): optimize RISC0's guest program input read
  crates/l2/prover/src/backend/risc0.rs
  crates/l2/prover/src/guest_program/src/risc0/src/main.rs
Labels: L2, prover

#4685 ci(l1): remove flamegraph and import block reports
  .github/workflows/common_failure_alerts.yaml
  .github/workflows/main_flamegraph_report.yaml
  .github/workflows/main_perf_blocks_exec.yml
  .github/workflows/pr-main_mdbook.yml
  .github/workflows/pr-main_replay_proving.yaml
Labels: L1

#4619 docs(replay): update docs with recent info
  docs/SUMMARY.md
  docs/ethrex_replay/ethrex_replay.md
  docs/ethrex_replay/faq.md
  docs/ethrex_replay/profiling.md
Labels: replay

#4704 chore(replay): remove `ethrex-replayer` bin
  Cargo.lock
  Cargo.toml
  tooling/replayer/.gitignore
  tooling/replayer/Cargo.toml
  tooling/replayer/src/main.rs
Labels: replay

#4503 feat(l2): add support for external moongate server sp1
  Cargo.lock
  cmd/ethrex/l2/options.rs
  crates/l2/prover/Cargo.toml
  crates/l2/prover/src/backend/sp1.rs
  crates/l2/prover/src/config.rs
  crates/l2/prover/src/prover.rs
  docs/CLI.md
Labels: L2, prover
