Repository lambdaclass/ethrex, pull requests merged in 2025-06, with the labels that each got.

#3017 refactor(core): remove proverdb from levm_bench
  Cargo.lock
  crates/vm/levm/bench/revm_comparison/Cargo.toml
  crates/vm/levm/bench/revm_comparison/src/lib.rs
Labels: tech debt

#2991 chore(l2): remove `ethrex_l2` CLI
  Cargo.lock
  Cargo.toml
  Makefile
  README.md
  cmd/ethrex/Cargo.toml
  cmd/ethrex/l2/command.rs
  cmd/ethrex_l2/Cargo.toml
  cmd/ethrex_l2/README.md
  cmd/ethrex_l2/assets/config_create.cast.gif
  cmd/ethrex_l2/assets/config_delete.cast.gif
  cmd/ethrex_l2/assets/config_edit.cast.gif
  cmd/ethrex_l2/assets/config_set.cast.gif
  cmd/ethrex_l2/assets/stack_init.cast.gif
  cmd/ethrex_l2/assets/stack_restart.cast.gif
  cmd/ethrex_l2/rust-toolchain.toml
  cmd/ethrex_l2/src/cli.rs
  cmd/ethrex_l2/src/commands/autocomplete.rs
  cmd/ethrex_l2/src/commands/config.rs
  cmd/ethrex_l2/src/commands/info.rs
  cmd/ethrex_l2/src/commands/mod.rs
  cmd/ethrex_l2/src/commands/stack.rs
  cmd/ethrex_l2/src/commands/utils.rs
  cmd/ethrex_l2/src/commands/wallet.rs
  cmd/ethrex_l2/src/config.rs
  cmd/ethrex_l2/src/lib.rs
  cmd/ethrex_l2/src/main.rs
  cmd/ethrex_l2/src/utils/config/default_values.rs
  cmd/ethrex_l2/src/utils/config/mod.rs
  cmd/ethrex_l2/src/utils/messages.rs
  cmd/ethrex_l2/src/utils/mod.rs
  crates/l2/Makefile
  crates/l2/docs/README.md
  crates/l2/storage/src/rlp.rs
  crates/l2/storage/src/store.rs
Labels: L2

#2860 feat(l1): implement eth/69
  Cargo.lock
  crates/common/rlp/decode.rs
  crates/common/rlp/encode.rs
  crates/common/rlp/error.rs
  crates/common/types/block.rs
  crates/common/types/receipt.rs
  crates/networking/p2p/Cargo.toml
  crates/networking/p2p/peer_handler.rs
  crates/networking/p2p/rlpx/connection.rs
  crates/networking/p2p/rlpx/error.rs
  crates/networking/p2p/rlpx/eth/backend.rs
  crates/networking/p2p/rlpx/eth/eth68/mod.rs
  crates/networking/p2p/rlpx/eth/eth68/receipts.rs
  crates/networking/p2p/rlpx/eth/eth68/status.rs
  crates/networking/p2p/rlpx/eth/eth69/mod.rs
  crates/networking/p2p/rlpx/eth/eth69/receipts.rs
  crates/networking/p2p/rlpx/eth/eth69/status.rs
  crates/networking/p2p/rlpx/eth/mod.rs
  crates/networking/p2p/rlpx/eth/receipts.rs
  crates/networking/p2p/rlpx/eth/status.rs
  crates/networking/p2p/rlpx/eth/update.rs
  crates/networking/p2p/rlpx/message.rs
  crates/networking/rpc/Cargo.toml
  crates/networking/rpc/eth/block.rs
  crates/networking/rpc/types/receipt.rs
  crates/storage/store.rs
  crates/storage/store_db/libmdbx.rs
Labels: p2p, L1

#3065 ci(l2): fix tdx nix image building add ci to prevent regressions
  .github/workflows/pr-main_l2_tdx_build.yaml
  crates/l2/Cargo.toml
  crates/l2/tee/quote-gen/service.nix
Labels: bug

#3000 feat(l2): use ExecutionWitness for proving
  Cargo.lock
  cmd/ethrex_replay/src/cache.rs
  cmd/ethrex_replay/src/constants.rs
  cmd/ethrex_replay/src/fetcher.rs
  cmd/ethrex_replay/src/rpc/db.rs
  cmd/ethrex_replay/src/rpc/mod.rs
  cmd/ethrex_replay/src/run.rs
  crates/blockchain/blockchain.rs
  crates/common/trie/trie.rs
  crates/common/types/block_execution_witness.rs
  crates/l2/prover/zkvm/interface/src/execution.rs
  crates/l2/prover/zkvm/interface/src/io.rs
  crates/l2/prover/zkvm/interface/src/trie.rs
  crates/l2/sequencer/errors.rs
  crates/l2/sequencer/mod.rs
  crates/l2/sequencer/proof_coordinator.rs
  crates/l2/tee/quote-gen/Cargo.lock
  crates/l2/utils/prover/db.rs
  crates/l2/utils/prover/mod.rs
  crates/l2/utils/test_data_io.rs
  crates/vm/Cargo.toml
  crates/vm/lib.rs
  crates/vm/prover_db.rs
  crates/vm/witness_db.rs
Labels: rpc-api, prover

#2975 feat(l1): improve hive CI and targets in makefile
  .github/workflows/common_hive_reports.yaml
  .github/workflows/daily_reports.yaml
  .github/workflows/pr-main_l1.yaml
  Makefile
  crates/vm/levm/Makefile
  test_data/network/hive_clients/ethrex.yml
  test_data/network/hive_clients/ethrex_git.yml
  test_data/network/hive_clients/ethrex_local.yml
Labels: L1, ci

#3109 feat(levm): solidity printer 2.0
  crates/vm/levm/src/constants.rs
  crates/vm/levm/src/debug.rs
  crates/vm/levm/src/lib.rs
  crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs
  crates/vm/levm/src/vm.rs
  test_data/levm_print/Print.sol
  test_data/levm_print/PrintTest.sol
Labels: levm

#3076 feat(l1, l2): blockchain tests stateless execution
  .github/workflows/pr-main_l1.yaml
  Cargo.lock
  Makefile
  cmd/ef_tests/blockchain/Cargo.toml
  cmd/ef_tests/blockchain/test_runner.rs
  crates/blockchain/blockchain.rs
  crates/common/trie/trie.rs
  crates/l2/prover/zkvm/interface/src/execution.rs
Labels: prover

#3131 refactor(levm): remove contemplations for empty accounts in trie
  crates/vm/backends/levm/db.rs
  crates/vm/backends/levm/mod.rs
  crates/vm/levm/docs/faq.md
  crates/vm/levm/src/db/gen_db.rs
  crates/vm/levm/src/db/mod.rs
  crates/vm/levm/src/opcode_handlers/system.rs
  crates/vm/levm/src/utils.rs
  crates/vm/levm/src/vm.rs
Labels: levm

#3143 refactor(levm): improve handle_opcode functions
  crates/vm/levm/src/call_frame.rs
  crates/vm/levm/src/constants.rs
  crates/vm/levm/src/errors.rs
  crates/vm/levm/src/execution_handlers.rs
  crates/vm/levm/src/hooks/default_hook.rs
  crates/vm/levm/src/hooks/l2_hook.rs
  crates/vm/levm/src/opcode_handlers/system.rs
  crates/vm/levm/src/utils.rs
  crates/vm/levm/src/vm.rs
Labels: levm

#3157 ci(l2): follow logs before running tests
  .github/workflows/pr-main_l2.yaml
Labels: L2, ci

#3087 feat(levm): add solidity printer
  cmd/ethrex/Cargo.toml
  crates/vm/Cargo.toml
  crates/vm/levm/Cargo.toml
  crates/vm/levm/docs/debug.md
  crates/vm/levm/src/debug.rs
  crates/vm/levm/src/lib.rs
  crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs
  crates/vm/levm/src/vm.rs
  test_data/levm_print/Print.sol
Labels: levm

#3148 feat(l2): read test variables from env
  crates/l2/tests/tests.rs
Labels: L2

#3199 refactor(levm): tidy code of benchmarks against revm
  crates/vm/levm/Makefile
  crates/vm/levm/bench/revm_comparison/README.md
  crates/vm/levm/bench/revm_comparison/src/benchmark.rs
  crates/vm/levm/bench/revm_comparison/src/compile.rs
  crates/vm/levm/bench/revm_comparison/src/levm_bench.rs
  crates/vm/levm/bench/revm_comparison/src/lib.rs
  crates/vm/levm/bench/revm_comparison/src/revm_bench.rs
Labels: tech debt, levm

#3134 refactor(levm): make substate more accurate and replace ExecutionReport for ContextResult in some places
  crates/vm/levm/src/call_frame.rs
  crates/vm/levm/src/constants.rs
  crates/vm/levm/src/errors.rs
  crates/vm/levm/src/execution_handlers.rs
  crates/vm/levm/src/hooks/backup_hook.rs
  crates/vm/levm/src/hooks/default_hook.rs
  crates/vm/levm/src/hooks/hook.rs
  crates/vm/levm/src/hooks/l2_hook.rs
  crates/vm/levm/src/opcode_handlers/logging.rs
  crates/vm/levm/src/opcode_handlers/system.rs
  crates/vm/levm/src/tracing.rs
  crates/vm/levm/src/utils.rs
  crates/vm/levm/src/vm.rs
Labels: tech debt, levm

#3238 feat(l1, l2): overwrite txs in mempool if fees are higher
  crates/blockchain/blockchain.rs
  crates/blockchain/mempool.rs
Labels: L2, L1

#3175 refactor(l2): use hardcoded vk in Aligned mode
  crates/l2/contracts/bin/deployer/main.rs
  crates/l2/contracts/src/l1/OnChainProposer.sol
  crates/l2/contracts/src/l1/interfaces/IOnChainProposer.sol
  crates/l2/prover/src/backends/sp1.rs
  crates/l2/prover/zkvm/interface/build.rs
  crates/l2/sequencer/errors.rs
  crates/l2/sequencer/l1_proof_verifier.rs
  crates/l2/utils/prover/proving_systems.rs
  crates/networking/rpc/clients/eth/mod.rs
  docs/l2/aligned_mode.md
Labels: L2

#3276 feat(l2): use all RPCs when using Aligned SDK
  cmd/ethrex/l2/options.rs
  crates/l2/sequencer/configs.rs
  crates/l2/sequencer/l1_proof_sender.rs
  crates/l2/sequencer/l1_proof_verifier.rs
  docs/l2/aligned_mode.md
Labels: L2

#3277 chore(l2): remove nested workspace
  crates/l2/prover/zkvm/Cargo.toml
Labels: tech debt, L2

#3297 fix(l2): remove withdrawals processing in build_payload
  crates/l2/sequencer/block_producer/payload_builder.rs
Labels: L2

#3288 refactor(l1): `SIGTERM` handling
  .github/workflows/main_prover.yaml
  Cargo.lock
  cmd/ethrex/ethrex.rs
  crates/blockchain/Cargo.toml
  crates/blockchain/blockchain.rs
  crates/l2/Makefile
  crates/networking/p2p/sync.rs
Labels: tech debt, L1

#3280 test(l1): run all blockchain tests and refactor logic
  cmd/ef_tests/blockchain/Cargo.toml
  cmd/ef_tests/blockchain/network.rs
  cmd/ef_tests/blockchain/test_runner.rs
  cmd/ef_tests/blockchain/tests/all.rs
  cmd/ef_tests/blockchain/tests/cancun.rs
  cmd/ef_tests/blockchain/tests/prague.rs
  cmd/ef_tests/blockchain/tests/shanghai.rs
Labels: ef-tests

#3293 fix(l1, levm): fix remaining blockchain test
  cmd/ef_tests/blockchain/tests/all.rs
  crates/vm/backends/levm/mod.rs
  crates/vm/backends/revm/mod.rs
  crates/vm/levm/src/db/gen_db.rs
  crates/vm/levm/src/hooks/default_hook.rs
Labels: ef-tests, levm, L1

#3342 ci(l2): build docker images for all l2 tests
  .github/workflows/pr-main_l2.yaml
Labels: L2, ci

#3273 chore(core): add install script
  README.md
  install.sh
Labels: docs, L1, tooling

#3332 perf(core): improve u256 handling, improving PUSH and other opcodes
  CHANGELOG.md
  crates/common/common.rs
  crates/common/utils.rs
  crates/vm/levm/src/execution_handlers.rs
  crates/vm/levm/src/memory.rs
  crates/vm/levm/src/opcode_handlers/block.rs
  crates/vm/levm/src/opcode_handlers/environment.rs
  crates/vm/levm/src/opcode_handlers/keccak.rs
  crates/vm/levm/src/opcode_handlers/push.rs
  crates/vm/levm/src/precompiles.rs
  crates/vm/levm/src/utils.rs
Labels: performance

#3356 perf(levm): reduce handle_debug runtime cost
  CHANGELOG.md
  crates/vm/levm/src/debug.rs
  crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs
Labels: performance

#3326 refactor(l2): remove blobs logic from payload_builder
  crates/l2/sequencer/block_producer/payload_builder.rs
Labels: L2

#3119 chore(l2): remove save state module
  Cargo.lock
  cmd/ethrex/l2/command.rs
  crates/l2/Makefile
  crates/l2/common/src/calldata.rs
  crates/l2/common/src/lib.rs
  crates/l2/common/src/prover.rs
  crates/l2/contracts/Cargo.toml
  crates/l2/contracts/bin/deployer/main.rs
  crates/l2/prover/Cargo.toml
  crates/l2/prover/src/backends/exec.rs
  crates/l2/prover/src/backends/sp1.rs
  crates/l2/prover/src/prover.rs
  crates/l2/prover/zkvm/interface/src/execution.rs
  crates/l2/sdk/Cargo.toml
  crates/l2/sdk/src/calldata.rs
  crates/l2/sdk/src/l1_to_l2_tx_data.rs
  crates/l2/sdk/src/sdk.rs
  crates/l2/sequencer/errors.rs
  crates/l2/sequencer/l1_committer.rs
  crates/l2/sequencer/l1_proof_sender.rs
  crates/l2/sequencer/l1_proof_verifier.rs
  crates/l2/sequencer/mod.rs
  crates/l2/sequencer/proof_coordinator.rs
  crates/l2/sequencer/setup.rs
  crates/l2/sequencer/utils.rs
  crates/l2/storage/Cargo.toml
  crates/l2/storage/src/api.rs
  crates/l2/storage/src/store.rs
  crates/l2/storage/src/store_db/in_memory.rs
  crates/l2/storage/src/store_db/libmdbx.rs
  crates/l2/storage/src/store_db/redb.rs
  crates/l2/storage/src/store_db/sql.rs
  crates/l2/tee/quote-gen/Cargo.lock
  crates/l2/tee/quote-gen/src/main.rs
  crates/l2/tee/quote-gen/src/sender.rs
  crates/l2/tests/tests.rs
  crates/l2/utils/mod.rs
  crates/l2/utils/prover/errors.rs
  crates/l2/utils/prover/mod.rs
  crates/l2/utils/prover/save_state.rs
  tooling/load_test/Cargo.toml
  tooling/load_test/src/main.rs
Labels: L2

#3357 ci(l2): use build-push-action to build L1 dev docker image
  .github/workflows/pr-main_l2.yaml
Labels: L2, ci

#3242 feat(l2): verify batches in chunks with aligned
  cmd/ethrex/l2/options.rs
  crates/l2/contracts/src/l1/OnChainProposer.sol
  crates/l2/contracts/src/l1/based/OnChainProposer.sol
  crates/l2/contracts/src/l1/based/interfaces/IOnChainProposer.sol
  crates/l2/contracts/src/l1/interfaces/IOnChainProposer.sol
  crates/l2/sequencer/configs.rs
  crates/l2/sequencer/l1_proof_sender.rs
  crates/l2/sequencer/l1_proof_verifier.rs
  docs/l2/aligned_mode.md
Labels: L2

#3223 docs(l2): document ETH and ERC20 deposits/withdrawals
  docs/SUMMARY.md
  docs/l2/deposits.md
  docs/l2/overview.md
  docs/l2/withdrawals.md
Labels: docs, L2

#3404 fix(l2): based CI
  crates/l2/contracts/src/l1/based/OnChainProposer.sol
Labels: L2

#3333 feat(l2): add instance info to Grafana alerts
  crates/blockchain/metrics/docker-compose-metrics-alerts.overrides.yaml
  crates/blockchain/metrics/provisioning/grafana_provisioning/alerting/contact_points.json
Labels: L2

#3339 feat(l2): exchange commit hash in node-prover communication
  Cargo.lock
  cmd/ethrex/Cargo.toml
  cmd/ethrex/build.rs
  cmd/ethrex/utils.rs
  crates/l2/Cargo.toml
  crates/l2/build.rs
  crates/l2/prover/Cargo.toml
  crates/l2/prover/build.rs
  crates/l2/prover/src/prover.rs
  crates/l2/sequencer/proof_coordinator.rs
  crates/l2/tee/quote-gen/Cargo.lock
  crates/l2/tee/quote-gen/Cargo.toml
  crates/l2/tee/quote-gen/build.rs
  crates/l2/tee/quote-gen/src/main.rs
  crates/l2/tee/quote-gen/src/sender.rs
Labels: L2

#3367 refactor(l1, l2, levm): remove `l2` feature flag from crates `ethrex-vm` and `ethrex-levm`
  cmd/ef_tests/blockchain/test_runner.rs
  cmd/ef_tests/state/Cargo.toml
  cmd/ef_tests/state/runner/levm_runner.rs
  cmd/ethrex/Cargo.toml
  cmd/ethrex/bench/build_block_benchmark.rs
  cmd/ethrex/bench/import_blocks_benchmark.rs
  cmd/ethrex/cli.rs
  cmd/ethrex/ethrex.rs
  cmd/ethrex/initializers.rs
  cmd/ethrex/l2/command.rs
  cmd/ethrex_replay/Cargo.toml
  cmd/ethrex_replay/src/cli.rs
  cmd/ethrex_replay/src/run.rs
  crates/blockchain/blockchain.rs
  crates/blockchain/payload.rs
  crates/blockchain/tracing.rs
  crates/l2/Cargo.toml
  crates/l2/based/block_fetcher.rs
  crates/l2/prover/Cargo.toml
  crates/l2/prover/zkvm/interface/Cargo.toml
  crates/l2/prover/zkvm/interface/risc0/Cargo.toml
  crates/l2/prover/zkvm/interface/sp1/Cargo.toml
  crates/l2/prover/zkvm/interface/src/execution.rs
  crates/l2/sequencer/block_producer/payload_builder.rs
  crates/l2/sequencer/l1_committer.rs
  crates/l2/sequencer/mod.rs
  crates/l2/tee/quote-gen/Cargo.toml
  crates/l2/utils/prover/save_state.rs
  crates/networking/rpc/eth/transaction.rs
  crates/vm/Cargo.toml
  crates/vm/backends/levm/mod.rs
  crates/vm/backends/levm/tracing.rs
  crates/vm/backends/mod.rs
  crates/vm/backends/revm/mod.rs
  crates/vm/backends/revm/tracing.rs
  crates/vm/levm/Cargo.toml
  crates/vm/levm/bench/revm_comparison/src/levm_bench.rs
  crates/vm/levm/src/gas_cost.rs
  crates/vm/levm/src/hooks/hook.rs
  crates/vm/levm/src/hooks/mod.rs
  crates/vm/levm/src/l2_precompiles.rs
  crates/vm/levm/src/lib.rs
  crates/vm/levm/src/precompiles.rs
  crates/vm/levm/src/utils.rs
  crates/vm/levm/src/vm.rs
  crates/vm/levm/tests/tests.rs
  crates/vm/tracing.rs
Labels: levm, L2, L1, simplification
