Repository lambdaclass/ethrex, pull requests merged in 2025-08, with the labels that each got.

#3860 ci(l1): update to new ethereum package version.
  .github/config/assertoor/network_params_blob.yaml
  .github/config/assertoor/network_params_ethrex_multiple_cl.yaml
  .github/config/assertoor/network_params_tx.yaml
  .github/workflows/pr-main_l1.yaml
  Makefile
  cmd/ethrex/initializers.rs
  fixtures/network/network_params.yaml
  fixtures/network/network_params_client_comparision.yaml
  fixtures/network/network_params_ethrex_only.yaml
Labels: L1

#3917 ci(l1): try thing out with pr status (not for merging).
  .github/scripts/set-pr-status.js
Labels: L1

#3840 chore(l1): preventing errors to propagate to spawned
  Cargo.lock
  Cargo.toml
  cmd/ethrex/initializers.rs
  crates/l2/monitor/app.rs
  crates/l2/sequencer/l1_watcher.rs
  crates/l2/tee/quote-gen/Cargo.lock
  crates/networking/p2p/rlpx/connection/handshake.rs
  crates/networking/p2p/rlpx/connection/server.rs
Labels: L1

#3932 refactor(l2): improve error handling in `EthClient`'s `send_request_to_all`
  crates/networking/rpc/clients/eth/errors.rs
  crates/networking/rpc/clients/eth/mod.rs
Labels: L2

#3926 refactor(levm): use levm's own Account type
  cmd/ef_tests/state/report.rs
  cmd/ef_tests/state/runner/mod.rs
  cmd/ef_tests/state/runner/revm_runner.rs
  cmd/ef_tests/state/runner_v2/result_check.rs
  cmd/ef_tests/state/runner_v2/utils.rs
  cmd/ef_tests/state/utils.rs
  cmd/ethrex_replay/src/run.rs
  crates/common/types/account.rs
  crates/l2/sequencer/block_producer/payload_builder.rs
  crates/vm/backends/levm/mod.rs
  crates/vm/backends/mod.rs
  crates/vm/levm/runner/src/main.rs
  crates/vm/levm/src/account.rs
  crates/vm/levm/src/call_frame.rs
  crates/vm/levm/src/db/gen_db.rs
  crates/vm/levm/src/db/mod.rs
  crates/vm/levm/src/hooks/default_hook.rs
  crates/vm/levm/src/opcode_handlers/environment.rs
  crates/vm/levm/src/utils.rs
Labels: L1

#3567 ci(l1): set project status automatically for `ethrex_l1`.
  .github/scripts/set-pr-status.js
  .github/workflows/pr_github_status_l1.yaml
Labels: L1

#3923 chore(l1): downgrade rpc api read requests to debug.
  crates/l2/networking/rpc/l2/batch.rs
  crates/networking/rpc/engine/exchange_transition_config.rs
  crates/networking/rpc/engine/fork_choice.rs
  crates/networking/rpc/engine/payload.rs
  crates/networking/rpc/eth/account.rs
  crates/networking/rpc/eth/block.rs
  crates/networking/rpc/eth/client.rs
  crates/networking/rpc/eth/fee_market.rs
  crates/networking/rpc/eth/transaction.rs
  crates/networking/rpc/rpc.rs
Labels: L1

#3935 ci(l1): fix Docker Login CI.
  .github/workflows/pr-main_l1.yaml
Labels: L1

#3937 refactor(l2): use logs from receipt for the integration tests
  crates/l2/tests/tests.rs
Labels: L2

#3823 fix(levm): fix tracing delegatecall
  crates/vm/levm/src/opcode_handlers/system.rs
Labels: rpc-api, levm

#3947 fix(l1,l2): fix git branch and hash in `ethrex --version`
  Dockerfile
Labels: L2

#3950 fix(levm): ignore offset value when size is zero
  crates/vm/levm/src/opcode_handlers/block.rs
  crates/vm/levm/src/opcode_handlers/environment.rs
  crates/vm/levm/src/opcode_handlers/keccak.rs
  crates/vm/levm/src/opcode_handlers/logging.rs
  crates/vm/levm/src/opcode_handlers/stack_memory_storage_flow.rs
  crates/vm/levm/src/opcode_handlers/system.rs
  crates/vm/levm/src/utils.rs
Labels: levm

#3970 fix(l1): allow P2P init with `dev` feature
  cmd/ethrex/initializers.rs
Labels: L1

#3967 feat(l1): embed bootnodes for public networks inside binary
  cmd/ethrex/initializers.rs
  cmd/ethrex/networks.rs
Labels: L1

#3988 fix(l1): unhardcode snapshot paths
  crates/networking/p2p/peer_handler.rs
  crates/networking/p2p/sync.rs
  crates/networking/p2p/utils.rs
Labels: L1

#3795 refactor(l2): use recover_address from common types
  crates/networking/p2p/rlpx.rs
  crates/networking/p2p/rlpx/based.rs
  crates/networking/p2p/rlpx/l2/l2_connection.rs
  crates/networking/p2p/rlpx/l2/messages.rs
  crates/networking/p2p/rlpx/utils.rs
Labels: p2p, tech debt, L2, based

#3913 refactor(l1,levm): improve levm `Database` and `Account`
  cmd/ef_tests/state/report.rs
  cmd/ef_tests/state/runner/levm_runner.rs
  cmd/ef_tests/state/runner/mod.rs
  cmd/ef_tests/state/runner/revm_runner.rs
  cmd/ef_tests/state/runner_v2/result_check.rs
  cmd/ef_tests/state/runner_v2/utils.rs
  cmd/ef_tests/state/utils.rs
  cmd/ethrex_replay/src/run.rs
  crates/common/types/account.rs
  crates/l2/Cargo.toml
  crates/l2/sequencer/block_producer/payload_builder.rs
  crates/vm/backends/levm/db.rs
  crates/vm/backends/levm/mod.rs
  crates/vm/backends/mod.rs
  crates/vm/levm/bench/revm_comparison/src/levm_bench.rs
  crates/vm/levm/runner/src/main.rs
  crates/vm/levm/src/account.rs
  crates/vm/levm/src/call_frame.rs
  crates/vm/levm/src/db/gen_db.rs
  crates/vm/levm/src/db/mod.rs
  crates/vm/levm/src/hooks/default_hook.rs
  crates/vm/levm/src/lib.rs
  crates/vm/levm/src/opcode_handlers/environment.rs
  crates/vm/levm/src/utils.rs
  docs/vm/levm/faq.md
Labels: levm, L1

#3999 refactor(l2): remove ProofCoordinator dev_mode
  .github/workflows/main_prover.yaml
  .github/workflows/pr-main_l2_tdx.yaml
  cmd/ethrex/l2/options.rs
  crates/l2/Makefile
  crates/l2/docker-compose.yaml
  crates/l2/sequencer/configs.rs
  crates/l2/sequencer/l1_proof_sender.rs
  crates/l2/sequencer/mod.rs
  crates/l2/sequencer/utils.rs
  docs/l2/aligned_mode.md
  docs/l2/tdx.md
Labels: L2

#3927 fix(l1): commit forkchoice update in a single db tx
  cmd/ethrex/cli.rs
  cmd/ethrex/initializers.rs
  cmd/ethrex/l2/command.rs
  crates/blockchain/fork_choice.rs
  crates/blockchain/mempool.rs
  crates/blockchain/smoke_test.rs
  crates/l2/based/state_updater.rs
  crates/networking/p2p/discv4/server.rs
  crates/networking/p2p/sync.rs
  crates/networking/rpc/eth/mod.rs
  crates/storage/api.rs
  crates/storage/store.rs
  crates/storage/store_db/in_memory.rs
  crates/storage/store_db/libmdbx.rs
  crates/storage/store_db/redb.rs
  tooling/archive_sync/src/main.rs
Labels: L1

#3240 feat(l1, l2, levm): profiling metrics
  Cargo.lock
  cmd/ethrex/ethrex.rs
  cmd/ethrex/initializers.rs
  crates/blockchain/blockchain.rs
  crates/blockchain/metrics/Cargo.toml
  crates/blockchain/metrics/api.rs
  crates/blockchain/metrics/mod.rs
  crates/blockchain/metrics/profiling.rs
  crates/l2/prover/zkvm/interface/risc0/Cargo.lock
  crates/l2/prover/zkvm/interface/sp1/Cargo.lock
  crates/storage/store.rs
  crates/vm/backends/mod.rs
  metrics/provisioning/grafana/dashboards/common_dashboards/execution_profile.json
  tooling/sync/Makefile
  tooling/sync/README.md
Labels: L2, L1

#3998 fix(l1): load Store state when exporting blocks
  cmd/ethrex/cli.rs
  cmd/ethrex/initializers.rs
  crates/storage/store.rs
Labels: L1

#3978 docs(l1,l2): refactor documentation
  .github/workflows/pr_lint_readme.yaml
  docs/CLI.md
  docs/SUMMARY.md
  docs/developers/README.md
  docs/developers/installing.md
  docs/developers/l1/dev-mode.md
  docs/developers/l1/importing-blocks.md
  docs/developers/l1/introduction.md
  docs/developers/l1/kurtosis-localnet.md
  docs/developers/l1/metrics.md
  docs/developers/l1/testing/README.md
  docs/developers/l1/testing/assertoor.md
  docs/developers/l1/testing/ef-tests.md
  docs/developers/l1/testing/hive.md
  docs/developers/l1/testing/load-tests.md
  docs/developers/l1/testing/rust.md
  docs/developers/l2/dev-mode.md
  docs/developers/l2/introduction.md
  docs/developers/l2/load_tests.md
  docs/ethrex_replay/ethrex_replay.md
  docs/getting-started/README.md
  docs/getting-started/consensus_client.md
  docs/getting-started/installation/binary_distribution.md
  docs/getting-started/installation/building_from_source.md
  docs/getting-started/installation/docker_images.md
  docs/getting-started/installation/installation.md
  docs/getting-started/installation/package_manager.md
  docs/getting-started/installing.md
  docs/getting-started/running.md
  docs/internal/l1/syncing_holesky.md
  docs/internal/l2/README.md
  docs/l1/dev-setup-l1.md
  docs/l1/fundamentals/networking/Network.md
  docs/l1/fundamentals/networking/Sync.md
  docs/l1/fundamentals/networking/diagrams/SnapSync.drawio.png
  docs/l1/fundamentals/networking/diagrams/StateSyncAndHealing.drawio.png
  docs/l1/fundamentals/networking/diagrams/bytecode_fetcher.jpg
  docs/l1/fundamentals/sync_modes.md
  docs/l1/running.md
  docs/l2/README.md
  docs/l2/based/contracts.md
  docs/l2/based/roadmap.md
  docs/l2/based/sequencer.md
  docs/l2/fundamentals/components/aligned_mode.md
  docs/l2/fundamentals/components/components.md
  docs/l2/fundamentals/components/prover.md
  docs/l2/fundamentals/components/sequencer.md
  docs/l2/fundamentals/components/tdx.md
  docs/l2/fundamentals/contracts.md
  docs/l2/fundamentals/deposits.md
  docs/l2/fundamentals/state_diffs.md
  docs/l2/fundamentals/withdrawals.md
  docs/l2/getting_started.md
  docs/l2/guides/depositing.md
  docs/l2/overview.md
  docs/l2/running.md
  docs/vm/levm/debug.md
Labels: docs, L2, L1

#4001 fix(l1): re-tag image as latest in hive report
  .github/workflows/common_hive_reports.yaml
Labels: L1

#4009 docs(l2): fix ethrex contracts download link
  docs/l2/running.md
Labels: docs, L2

#4003 refactor(levm): move `get_state_transitions` logic to `GeneralizedDatabase`
  crates/vm/backends/levm/mod.rs
  crates/vm/levm/src/db/gen_db.rs
Labels: levm

#3962 feat(l1): add `--input_dir` and `--output_dir` options to archive sync
  crates/common/serde_utils.rs
  crates/networking/rpc/clients/beacon/types.rs
  tooling/archive_sync/README.md
  tooling/archive_sync/src/main.rs
Labels: L1

#4030 fix(l1): fix off-by-one in update_pivot
  crates/networking/p2p/peer_handler.rs
  crates/networking/p2p/sync.rs
Labels: L1

#4022 chore(l1): improve log message when trying to run incompatible configs
  crates/storage/error.rs
  crates/storage/store.rs
Labels: L1

#4033 fix(l1): byte comparison with usize wrong in 32 bit architecture
  crates/common/types/requests.rs
Labels: L1

#4048 fix(l2): disable gpu in `make lint` target
  .github/workflows/pr-main_l1.yaml
  .github/workflows/pr-main_l2.yaml
  Makefile
Labels: L2

#4045 perf(levm): use malachite for modexp
  CHANGELOG.md
  Cargo.lock
  crates/l2/prover/zkvm/interface/risc0/Cargo.lock
  crates/l2/prover/zkvm/interface/sp1/Cargo.lock
  crates/l2/tee/quote-gen/Cargo.lock
  crates/vm/levm/Cargo.toml
  crates/vm/levm/src/gas_cost.rs
  crates/vm/levm/src/precompiles.rs
Labels: performance

#4050 fix(l1): restore datadir path
  cmd/ethrex/utils.rs
Labels: L1

#3984 refactor(l2): remove WrappedTransaction
  cmd/ethrex/l2/deployer.rs
  crates/common/types/transaction.rs
  crates/l2/networking/rpc/clients.rs
  crates/l2/sdk/src/l1_to_l2_tx_data.rs
  crates/l2/sdk/src/sdk.rs
  crates/l2/sequencer/l1_committer.rs
  crates/l2/sequencer/l1_watcher.rs
  crates/l2/sequencer/setup.rs
  crates/l2/sequencer/utils.rs
  crates/l2/tests/tests.rs
  crates/networking/rpc/clients/eth/errors.rs
  crates/networking/rpc/clients/eth/mod.rs
  tooling/load_test/src/main.rs
Labels: L2

#4070 perf(levm): improve perf of calldataload, calldatacopy, extcodecopy, codecopy, returndatacopy
  CHANGELOG.md
  crates/vm/levm/src/opcode_handlers/environment.rs
Labels: performance

#4071 perf(levm): improve signextend opcode performance
  CHANGELOG.md
  crates/vm/levm/src/opcode_handlers/arithmetic.rs
Labels: performance

#4051 fix(l1): subtract DB read times from block execution.
  crates/storage/store.rs
  metrics/provisioning/grafana/dashboards/common_dashboards/ethrex_l1_perf.json
Labels: L1

#4085 refactor(levm): change ecrecover implementation to use k256 instead of secp256k1
  Cargo.lock
  crates/l2/prover/zkvm/interface/risc0/Cargo.lock
  crates/l2/prover/zkvm/interface/sp1/Cargo.lock
  crates/vm/levm/Cargo.toml
  crates/vm/levm/src/precompiles.rs
Labels: levm

#4103 chore(l1): remove redb support
  .gitignore
  Cargo.lock
  Cargo.toml
  Makefile
  cmd/ethrex/Cargo.toml
  cmd/ethrex/initializers.rs
  cmd/ethrex/l2/command.rs
  crates/storage/Cargo.toml
  crates/storage/error.rs
  crates/storage/lib.rs
  crates/storage/rlp.rs
  crates/storage/store.rs
  crates/storage/store_db/mod.rs
  crates/storage/store_db/redb.rs
  crates/storage/trie_db/mod.rs
  crates/storage/trie_db/redb.rs
  crates/storage/trie_db/redb_multitable.rs
  crates/storage/trie_db/utils.rs
  docs/developers/installing.md
Labels: L1

#3992 fix(l1): `ethrex-replay` block execution in different networks
  .gitignore
  Cargo.lock
  Cargo.toml
  cmd/ef_tests/blockchain/test_runner.rs
  cmd/ethrex/Cargo.toml
  cmd/ethrex/bench/import_blocks_benchmark.rs
  cmd/ethrex/cli.rs
  cmd/ethrex/ethrex.rs
  cmd/ethrex/initializers.rs
  cmd/ethrex/l2/command.rs
  cmd/ethrex/l2/deployer.rs
  cmd/ethrex/lib.rs
  cmd/ethrex_replay/Cargo.toml
  cmd/ethrex_replay/src/cache.rs
  cmd/ethrex_replay/src/cli.rs
  cmd/ethrex_replay/src/constants.rs
  cmd/ethrex_replay/src/fetcher.rs
  cmd/ethrex_replay/src/main.rs
  crates/blockchain/blockchain.rs
  crates/common/config/Cargo.toml
  crates/common/config/lib.rs
  crates/common/config/networks.rs
  crates/common/rkyv_utils.rs
  crates/common/types/block_execution_witness.rs
  crates/l2/prover/zkvm/interface/src/execution.rs
  crates/networking/rpc/Cargo.toml
  crates/networking/rpc/clients/eth/mod.rs
  crates/networking/rpc/debug/execution_witness.rs
  crates/networking/rpc/debug/mod.rs
  crates/networking/rpc/eth/block.rs
  crates/networking/rpc/lib.rs
  crates/networking/rpc/rpc.rs
Labels: L2, L1, tooling

#4076 fix(l1): `ethrex_replay` reduce cases were OOM happen with SP1
  cmd/ethrex_replay/src/run.rs
  crates/blockchain/blockchain.rs
  crates/common/trie/trie.rs
  crates/common/types/block_execution_witness.rs
  crates/l2/prover/zkvm/interface/sp1/Cargo.lock
  crates/l2/prover/zkvm/interface/src/execution.rs
  crates/l2/tee/quote-gen/Cargo.lock
  crates/networking/rpc/debug/execution_witness.rs
Labels: L2, L1

#4104 fix(levm): fix problems related to 32 bit architecture
  crates/vm/levm/src/constants.rs
  crates/vm/levm/src/memory.rs
  crates/vm/levm/src/utils.rs
Labels: L1

#4080 feat(l1): snap sync fix ci
  cmd/ethrex/ethrex.rs
  crates/blockchain/mempool.rs
  crates/l2/tee/quote-gen/Cargo.lock
  crates/networking/p2p/p2p.rs
  crates/networking/p2p/peer_handler.rs
  crates/networking/p2p/rlpx/connection/server.rs
  crates/networking/p2p/sync.rs
  crates/networking/p2p/tx_broadcaster.rs
  crates/networking/p2p/types.rs
  crates/networking/rpc/utils.rs
  crates/storage/store_db/redb.rs
Labels: L1

#4102 ci(l1): skip some internal jobs for external contributions.
  .github/workflows/pr_github_metadata.yaml
  .github/workflows/pr_github_status_l1.yaml
Labels: L1

#4107 feat(l1,l2): add new commands to execution witness
  Cargo.lock
  cmd/ethrex_replay/src/block_run_report.rs
  cmd/ethrex_replay/src/cli.rs
  cmd/ethrex_replay/src/fetcher.rs
  cmd/ethrex_replay/src/main.rs
  cmd/ethrex_replay/src/run.rs
Labels: L2

#4073 perf(levm): improve bls12 precompile
  CHANGELOG.md
  crates/vm/levm/src/precompiles.rs
Labels: performance

#4128 refactor(l2): change usize state diff constants
  Cargo.lock
  crates/l2/common/Cargo.toml
  crates/l2/common/src/state_diff.rs
  crates/l2/monitor/widget/l2_to_l1_messages.rs
  crates/l2/prover/zkvm/interface/risc0/Cargo.lock
  crates/l2/prover/zkvm/interface/sp1/Cargo.lock
  crates/l2/sequencer/block_producer/payload_builder.rs
  crates/l2/sequencer/errors.rs
Labels: L2

#4130 perf(levm): improve ecpairing (bn128)
  CHANGELOG.md
  crates/vm/levm/src/precompiles.rs
Labels: performance

#4129 ci(l1,l2): fix main_prover_l1 block cache
  .github/workflows/main_prover_l1.yaml
  fixtures/cache/rpc_prover/cache_3990967.json
  fixtures/cache/rpc_prover/cache_690403.json
  fixtures/cache/rpc_prover/cache_hoodi_1041734.json
  fixtures/cache/rpc_prover/cache_hoodi_974567.json
Labels: L2, prover

#4097 perf(levm): make precompiles use a constant table
  CHANGELOG.md
  crates/vm/levm/src/precompiles.rs
Labels: performance

#4151 fix(l2): use `spawned::start_blocking` for block_producer
  crates/l2/sequencer/block_producer.rs
Labels: L2

#4143 chore(l1): move `ef_tests` to `tooling`
  .github/workflows/main_flamegraph_report.yaml
  .github/workflows/pr-main_l1.yaml
  .github/workflows/pr-main_levm.yaml
  .gitignore
  Cargo.toml
  crates/vm/levm/Makefile
  crates/vm/levm/README.md
  tooling/ef_tests/blockchain/.fixtures_url
  tooling/ef_tests/blockchain/Cargo.toml
  tooling/ef_tests/blockchain/Makefile
  tooling/ef_tests/blockchain/README.md
  tooling/ef_tests/blockchain/deserialize.rs
  tooling/ef_tests/blockchain/lib.rs
  tooling/ef_tests/blockchain/network.rs
  tooling/ef_tests/blockchain/test_runner.rs
  tooling/ef_tests/blockchain/tests/all.rs
  tooling/ef_tests/blockchain/types.rs
  tooling/ef_tests/state/.fixtures_url
  tooling/ef_tests/state/Cargo.toml
  tooling/ef_tests/state/Makefile
  tooling/ef_tests/state/README.md
  tooling/ef_tests/state/deserialize.rs
  tooling/ef_tests/state/lib.rs
  tooling/ef_tests/state/parser.rs
  tooling/ef_tests/state/report.rs
  tooling/ef_tests/state/runner/levm_runner.rs
  tooling/ef_tests/state/runner/mod.rs
  tooling/ef_tests/state/runner/revm_runner.rs
  tooling/ef_tests/state/tests/all.rs
  tooling/ef_tests/state/types.rs
  tooling/ef_tests/state/utils.rs
  tooling/ef_tests/state_v2/.gitignore
  tooling/ef_tests/state_v2/Cargo.toml
  tooling/ef_tests/state_v2/Makefile
  tooling/ef_tests/state_v2/README.md
  tooling/ef_tests/state_v2/src/lib.rs
  tooling/ef_tests/state_v2/src/main.rs
  tooling/ef_tests/state_v2/src/modules/deserialize.rs
  tooling/ef_tests/state_v2/src/modules/error.rs
  tooling/ef_tests/state_v2/src/modules/mod.rs
  tooling/ef_tests/state_v2/src/modules/parser.rs
  tooling/ef_tests/state_v2/src/modules/report.rs
  tooling/ef_tests/state_v2/src/modules/result_check.rs
  tooling/ef_tests/state_v2/src/modules/runner.rs
  tooling/ef_tests/state_v2/src/modules/types.rs
  tooling/ef_tests/state_v2/src/modules/utils.rs
Labels: L1

#4165 refactor(l2): `ethrex_replay` reduce rpc requests by caching retrieved values
  Cargo.lock
  cmd/ethrex_replay/src/fetcher.rs
  cmd/ethrex_replay/src/rpc/db.rs
  cmd/ethrex_replay/src/rpc/mod.rs
  crates/networking/rpc/types/block.rs
Labels: L2

#4126 feat(l1): `ethrex_replay` add new command to create cache for block
  cmd/ethrex_replay/src/cli.rs
Labels: L1

#4173 fix(l2): remote grafana no data from a Linux system
  metrics/docker-compose-metrics-l2.overrides.yaml
Labels: L2

#4135 test(l1): add possibility of running Blockchain EFTests with SP1
  Cargo.lock
  tooling/ef_tests/blockchain/Cargo.toml
  tooling/ef_tests/blockchain/Makefile
  tooling/ef_tests/blockchain/test_runner.rs
  tooling/ef_tests/blockchain/tests/all.rs
Labels: L2, L1

#4113 fix(l2): log errors in send_generic_transaction, improve web3signer errors
  crates/l2/networking/rpc/clients.rs
  crates/l2/networking/rpc/signer.rs
Labels: L2

#3825 refactor(l1,l2): rename genserver errors
  crates/l2/based/block_fetcher.rs
  crates/l2/based/state_updater.rs
  crates/l2/sequencer/block_producer.rs
  crates/l2/sequencer/errors.rs
  crates/l2/sequencer/l1_committer.rs
  crates/l2/sequencer/l1_proof_sender.rs
  crates/l2/sequencer/l1_watcher.rs
  crates/l2/sequencer/metrics.rs
  crates/l2/sequencer/proof_coordinator.rs
Labels: L2

#4168 perf(levm): improvements to precompiles
  CHANGELOG.md
  crates/vm/levm/src/errors.rs
  crates/vm/levm/src/precompiles.rs
Labels: performance

#4192 build(l1, l2): tag `ethrex:main` instead of `ethrex:unstable`.
  .github/workflows/common_hive_reports.yaml
  .github/workflows/main_docker_publish.yaml
  .github/workflows/pr-main_l2.yaml
  Makefile
  crates/l2/docker-compose.yaml
  docs/getting-started/installation/docker_images.md
Labels: L2

#4172 feat(l1, l2): preprocess execution witness data
  crates/blockchain/blockchain.rs
  crates/common/trie/trie.rs
  crates/common/types/block_execution_witness.rs
  crates/l2/prover/zkvm/interface/src/execution.rs
  crates/l2/tee/quote-gen/Cargo.lock
  crates/networking/rpc/debug/execution_witness.rs
Labels: L2

#4194 feat(l2): revert batch subcommand with web3signer
  cmd/ethrex/l2/command.rs
  crates/l2/sdk/src/sdk.rs
Labels: L2

#4197 feat(l2): rich accounts monitor tab
  Cargo.lock
  crates/l2/Cargo.toml
  crates/l2/monitor/app.rs
  crates/l2/monitor/widget/mod.rs
  crates/l2/monitor/widget/rich_accounts.rs
  crates/l2/monitor/widget/tabs.rs
  crates/l2/sequencer/errors.rs
Labels: L2

#4205 perf(l1): avoid cloning the mempool keys when filtering
  CHANGELOG.md
  crates/blockchain/mempool.rs
Labels: performance

#4186 feat(l2): add support for multiple networks on a single prover
  cmd/ethrex/l2/options.rs
  crates/l2/Makefile
  crates/l2/docker-compose.yaml
  crates/l2/prover/src/config.rs
  crates/l2/prover/src/prover.rs
  docs/CLI.md
  docs/l2/running.md
Labels: L2, prover
